import { useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useParams } from 'react-router-dom'
import { ArrowRight, BadgeCheck, CalendarDays, Check, ChevronDown, CircleDollarSign, Clock3, ExternalLink, Globe2, Layers3, Link2, MapPin, Plus, ShieldCheck, SlidersHorizontal, Sparkles, Store, Ticket, Trash2, Users, Wine, X } from 'lucide-react'
import { demoApprovals, demoEvents, demoFeeConfiguration, demoMemberships, demoOffers, demoPartnerProfiles, demoPlacements, demoWinerySections, demoWorkspaces } from './data/business'
import { producers, regions, wines } from './data/catalog'
import { repository } from './data/repository'
import { useLocale } from './i18n'
import { useUiCopy } from './uiCopy'
import type { BusinessWorkspace, EventModality, EventVisibility, MerchantOffer, PartnerProfile, PromotionalPlacement, PublishState, TastingEvent, WineryPageSection } from './types'
import vineyardHero from './assets/vineyard-terraces.jpg'
import tastingStill from './assets/tasting-still-life.jpg'

type Ui=ReturnType<typeof useUiCopy>

const money=(minor:number,currency:string,locale:string)=>new Intl.NumberFormat(locale,{style:'currency',currency}).format(minor/100)
const dateTime=(value:string,locale:string)=>new Intl.DateTimeFormat(locale,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value))
const eventCopy=(event:TastingEvent,ui:Ui)=>event.id==='riesling-latitude-light'?{title:ui.eventOneTitle,summary:ui.eventOneSummary}:event.id==='marlborough-beyond-citrus'?{title:ui.eventTwoTitle,summary:ui.eventTwoSummary}:event.id==='pinot-place-table'?{title:ui.eventThreeTitle,summary:ui.eventThreeSummary}:event.id==='private-cellar-circle'?{title:ui.eventPrivateTitle,summary:ui.eventPrivateSummary}:{title:event.title,summary:event.summary}
const profileCopy=(profile:PartnerProfile,ui:Ui)=>profile.kind==='host'?{tagline:ui.hostTagline,story:ui.hostStory}:profile.kind==='winery'?{tagline:ui.wineryTagline,story:ui.wineryStory}:{tagline:ui.merchantTagline,story:ui.merchantStory}
const modalityLabel=(value:EventModality,ui:Ui)=>value==='online'?ui.online:value==='in-person'?ui.inPerson:ui.hybrid
const statusLabel=(value:string,ui:Ui)=>value==='verified'?ui.verified:value==='pending'?ui.verificationPending:value==='published'?ui.published:value==='paused'?ui.paused:value==='approved'?ui.approved:value==='rejected'?ui.rejected:value==='enabled'?ui.enabled:value==='disabled'?ui.disabled:value==='unverified'?ui.unverified:ui.draft
const roleLabel=(value:string,ui:Ui)=>value==='host'?ui.professionalHost:value==='winery'?ui.winery:value==='merchant'?ui.merchant:value==='admin'?ui.adminRole:ui.privateMember
const visibilityLabel=(value:EventVisibility,ui:Ui)=>value==='public'?ui.publicLabel:value==='unlisted'?ui.unlisted:ui.privateLabel
const planLabel=(value:BusinessWorkspace['plan'],ui:Ui)=>value==='member'?ui.privateMember:value==='studio'?ui.studioNav:value==='partner'?ui.partnerProfile:ui.configurable
const checklistLabel=(value:string,ui:Ui)=>value==='profile'?ui.publicProfile:value==='cellar'?ui.cellarLabel:value==='private-tasting'?`${ui.privateLabel} · ${ui.eventsNav}`:value==='event'?ui.createEvent:value==='storyline'?ui.storyline:value==='payouts'?ui.secureInfrastructure:value==='claim'?ui.verification:value==='story'?ui.storySection:value==='wines'?ui.winesSection:value==='verification'?ui.verification:value==='markets'?ui.market:value==='offer'?ui.addOffer:value==='relations'?ui.reviewRelations:value==='approvals'?ui.approvalQueue:ui.placementTitle
const approvalKindLabel=(value:string,ui:Ui)=>value==='role-application'?ui.role:value==='winery-claim'?ui.winery:value==='wine-change'?ui.wine:value==='public-event'?ui.eventsNav:value==='offer'?ui.offersTitle:ui.reviewRelations
const sectionTypeLabel=(value:WineryPageSection['type'],ui:Ui)=>({hero:ui.heroSection,story:ui.storySection,vineyards:ui.vineyardsSection,cellar:ui.cellarSection,visits:ui.visitsSection,team:ui.teamSection,gallery:ui.gallerySection,wines:ui.winesSection,contact:ui.contactSection}[value])
const sectionSeedCopy=(section:WineryPageSection,ui:Ui)=>{
  const seed:Record<string,{heading:string;body:string}>={
    'section-hero':{heading:ui.wineryTagline,body:ui.wineryStory},
    'section-story':{heading:ui.storySection,body:ui.editorialContext},
    'section-vineyards':{heading:ui.vineyardsSection,body:ui.eventOneSummary},
    'section-cellar':{heading:ui.cellarSection,body:ui.eventTwoSummary},
    'section-wines':{heading:ui.winesSection,body:ui.reviewRelations},
    'section-visits':{heading:ui.visitsSection,body:ui.serviceArea},
  }
  return seed[section.id]??{heading:section.heading,body:section.body}
}

function BusinessIntro({eyebrow,title,children,action}:{eyebrow:string;title:string;children?:ReactNode;action?:ReactNode}){
  return <header className="business-intro"><div><span>{eyebrow}</span><h1>{title}</h1>{children}</div>{action}</header>
}

function StateBadge({state}:{state:string}){const ui=useUiCopy();return <span className={`business-state state-${state}`}><i/>{statusLabel(state,ui)}</span>}

function InfrastructureNotice(){const ui=useUiCopy();return <aside className="infrastructure-notice"><ShieldCheck/><div><strong>{ui.productionNotice}</strong><p>{ui.productionNoticeBody}</p></div><span>{ui.demoOnly}</span></aside>}

function EventCard({event}:{event:TastingEvent}){
  const {locale}=useLocale();const ui=useUiCopy();const content=eventCopy(event,ui);const region=regions.find(item=>item.id===event.regionId)
  return <Link to={`/events/${event.id}`} className="event-card">
    <div className="event-date"><strong>{new Intl.DateTimeFormat(locale,{day:'2-digit'}).format(new Date(event.startsAt))}</strong><span>{new Intl.DateTimeFormat(locale,{month:'short'}).format(new Date(event.startsAt))}</span></div>
    <div className="event-card-main"><div className="event-labels"><span>{modalityLabel(event.modality,ui)}</span><span>{event.ticket.type==='free'?ui.free:ui.paid}</span><span>{event.language.toUpperCase()}</span></div><h2>{content.title}</h2><p>{content.summary}</p><div className="event-meta"><span><CalendarDays/>{dateTime(event.startsAt,locale)}</span><span><MapPin/>{event.modality==='online'?ui.online:event.venue}</span>{region&&<span><Globe2/>{region.name}</span>}</div></div>
    <div className="event-card-ticket"><small>{ui.ticket}</small><strong>{event.ticket.type==='free'?ui.free:money(event.ticket.amountMinor,event.ticket.currency,locale)}</strong><span>{event.ticket.type==='paid'&&ui.pricePerGuest}</span><ArrowRight/></div>
  </Link>
}

export function EventsMarketplace(){
  const ui=useUiCopy();const [format,setFormat]=useState<'all'|EventModality>('all');const [price,setPrice]=useState<'all'|'free'|'paid'>('all');const [language,setLanguage]=useState('all');const [regionId,setRegionId]=useState('all');const [after,setAfter]=useState('');
  const events=repository.events.all(demoEvents).filter(event=>event.visibility==='public'&&event.publishState==='published')
  const filtered=events.filter(event=>(format==='all'||event.modality===format)&&(price==='all'||event.ticket.type===price)&&(language==='all'||event.language===language)&&(regionId==='all'||event.regionId===regionId)&&(!after||event.startsAt.slice(0,10)>=after))
  const reset=()=>{setFormat('all');setPrice('all');setLanguage('all');setRegionId('all');setAfter('')}
  return <div className="page business-page"><BusinessIntro eyebrow={ui.marketplace} title={ui.eventsTitle} action={<Link className="primary-button ink" to="/studio/events">{ui.createEvent}<ArrowRight/></Link>}><p>{ui.eventsBody}</p></BusinessIntro>
    <section className="marketplace-filters" aria-label={ui.filter}><label>{ui.format}<select value={format} onChange={event=>setFormat(event.target.value as typeof format)}><option value="all">{ui.allFormats}</option><option value="online">{ui.online}</option><option value="in-person">{ui.inPerson}</option><option value="hybrid">{ui.hybrid}</option></select></label><label>{ui.ticket}<select value={price} onChange={event=>setPrice(event.target.value as typeof price)}><option value="all">{ui.allPrices}</option><option value="free">{ui.free}</option><option value="paid">{ui.paid}</option></select></label><label>{ui.language}<select value={language} onChange={event=>setLanguage(event.target.value)}><option value="all">{ui.allLanguages}</option><option value="en">EN</option><option value="de">DE</option><option value="fr">FR</option><option value="es">ES</option></select></label><label>{ui.region}<select value={regionId} onChange={event=>setRegionId(event.target.value)}><option value="all">{ui.worldAtlas}</option>{regions.filter(region=>events.some(item=>item.regionId===region.id)).map(region=><option key={region.id} value={region.id}>{region.name}</option>)}</select></label><label>{ui.starts}<input type="date" value={after} onChange={event=>setAfter(event.target.value)}/></label><button onClick={reset}><X/>{ui.clear}</button></section>
    <div className="event-results-heading"><span>{String(filtered.length).padStart(2,'0')}</span><h2>{ui.upcoming}</h2></div>
    <section className="event-list">{filtered.length?filtered.map(event=><EventCard event={event} key={event.id}/>):<div className="business-empty"><CalendarDays/><h2>{ui.noEvents}</h2><p>{ui.noEventsBody}</p><button className="secondary-button" onClick={reset}>{ui.clear}</button></div>}</section>
  </div>
}

export function EventDetail(){
  const {id}=useParams();const {locale}=useLocale();const ui=useUiCopy();const event=repository.events.all(demoEvents).find(item=>item.id===id);const [checkout,setCheckout]=useState(false);const [cellarWineIds,setCellarWineIds]=useState(()=>new Set(repository.cellar.all().flatMap(item=>item.wineId?[item.wineId]:[])))
  if(!event)return <div className="page business-empty"><CalendarDays/><h1>{ui.noEvents}</h1><Link className="primary-button" to="/events">{ui.viewEvents}</Link></div>
  const content=eventCopy(event,ui);const host=demoPartnerProfiles.find(item=>item.id===event.hostProfileId)!;const region=regions.find(item=>item.id===event.regionId);const eventWines=wines.filter(wine=>event.featuredWineIds.includes(wine.id))
  const addWineToCellar=(wineId:string)=>{const cellar=repository.cellar.all();if(!cellar.some(item=>item.wineId===wineId)){cellar.push({id:crypto.randomUUID(),wineId,state:'owned',quantity:1,location:ui.homeCellar});repository.cellar.save(cellar)}setCellarWineIds(new Set([...cellarWineIds,wineId]))}
  return <div className="page business-page"><Link className="back-link" to="/events">← {ui.marketplace}</Link><section className="event-detail-hero"><div><div className="event-labels"><span>{modalityLabel(event.modality,ui)}</span><span>{event.language.toUpperCase()}</span><span>{event.ticket.type==='free'?ui.free:ui.paid}</span></div><h1>{content.title}</h1><p>{content.summary}</p><Link to={`/hosts/${host.id}`}>{ui.hostedBy} {host.displayName}<ArrowRight/></Link></div><div className="event-ticket-panel"><span>{ui.ticket}</span><strong>{event.ticket.type==='free'?ui.free:money(event.ticket.amountMinor,event.ticket.currency,locale)}</strong><small>{event.ticket.type==='paid'&&ui.pricePerGuest}</small><button className="primary-button" onClick={()=>setCheckout(true)}><Ticket/>{ui.reserveDemo}</button><p><ShieldCheck/>{ui.paymentFuture}</p></div></section>
    <section className="event-detail-grid"><article><span>{ui.start}</span><strong>{dateTime(event.startsAt,locale)}</strong><CalendarDays/></article><article><span>{ui.duration}</span><strong>{event.durationMinutes} {ui.minutes}</strong><Clock3/></article><article><span>{ui.capacity}</span><strong>{event.capacity} {ui.people}</strong><Users/></article><article><span>{ui.logistics}</span><strong>{event.modality==='online'?ui.joiningLinkSecure:event.venue}</strong><MapPin/></article></section>
    <section className="learning-itinerary"><div><span>{ui.learningItinerary}</span><h2>{ui.includedConnections}</h2><p>{ui.editorialContext}</p></div><ol><li><span>01</span><div><strong>{ui.wine}</strong><div className="event-wines-to-cellar">{eventWines.length?eventWines.map(wine=><div key={wine.id}><Link to={`/wines/${wine.id}`}>{wine.name}</Link><button disabled={cellarWineIds.has(wine.id)} onClick={()=>addWineToCellar(wine.id)}>{cellarWineIds.has(wine.id)?<><Check/>{ui.inYourCellar}</>:<><Plus/>{ui.addToCellar}</>}</button></div>):<p>{ui.storyline}</p>}</div></div></li>{region&&<li><span>02</span><div><strong>{ui.region}</strong><Link to={`/regions/${region.id}`}>{region.name}<ArrowRight/></Link></div></li>}<li><span>03</span><div><strong>{ui.chapterLesson}</strong><Link to="/learn">{ui.continueAtlas}<ArrowRight/></Link></div></li></ol></section>
    <section className="event-terms"><div><span>{ui.cancellation}</span><p>{event.cancellationTerms}</p></div><InfrastructureNotice/></section>
    {checkout&&<div className="business-modal" role="dialog" aria-modal="true" aria-label={ui.checkoutPreview}><div><button className="modal-close" onClick={()=>setCheckout(false)} aria-label={ui.close}><X/></button><span className="eyebrow">{ui.demoOnly}</span><h2>{ui.checkoutPreview}</h2><p>{ui.checkoutPreviewBody}</p><div className="checkout-line"><span>{content.title}</span><strong>{event.ticket.type==='free'?ui.free:money(event.ticket.amountMinor,event.ticket.currency,locale)}</strong></div><button className="primary-button ink" onClick={()=>setCheckout(false)}>{ui.continueDemo}</button></div></div>}
  </div>
}

export function HostProfile(){
  const {id}=useParams();const ui=useUiCopy();const profile=repository.partnerProfiles.all(demoPartnerProfiles).find(item=>item.id===id&&item.kind==='host');if(!profile)return <PartnerNotFound/>;const content=profileCopy(profile,ui);const events=repository.events.all(demoEvents).filter(item=>item.hostProfileId===profile.id&&item.visibility==='public'&&item.publishState==='published')
  return <div className="page business-page"><section className="partner-hero host-profile-hero"><div><span className="eyebrow">{ui.hostProfile}</span><h1>{profile.displayName}</h1><p className="lead">{content.tagline}</p><StateBadge state={profile.verification}/></div><img src={tastingStill} alt=""/></section><section className="partner-story"><div><span>{ui.professionalHost}</span><h2>{ui.hostStory}</h2><p>{content.story}</p></div><dl><div><dt>{ui.expertise}</dt><dd>{profile.expertise.join(' · ')}</dd></div><div><dt>{ui.languages}</dt><dd>{profile.languages.join(' · ')}</dd></div><div><dt>{ui.serviceArea}</dt><dd>{profile.serviceArea}</dd></div></dl></section><section className="studio-section"><header><span>{ui.upcomingEvents}</span><h2>{ui.eventsTitle}</h2></header><div className="event-list">{events.map(event=><EventCard event={event} key={event.id}/>)}</div></section></div>
}

function PartnerNotFound(){const ui=useUiCopy();return <div className="page business-empty"><Store/><h1>{ui.partnerProfile}</h1><Link className="primary-button" to="/atlas">{ui.openAtlas}</Link></div>}

export function PartnerProfilePage(){
  const {id}=useParams();const ui=useUiCopy();const profile=repository.partnerProfiles.all(demoPartnerProfiles).find(item=>item.id===id&&item.kind!=='host');if(!profile)return <PartnerNotFound/>;const content=profileCopy(profile,ui);const producer=producers.find(item=>item.id===profile.producerId);const sections=repository.winerySections.all(demoWinerySections).filter(section=>section.workspaceId===profile.workspaceId&&section.visible).sort((a,b)=>a.order-b.order);const offers=repository.offers.all(demoOffers).filter(offer=>offer.workspaceId===profile.workspaceId)
  return <div className="page business-page"><section className="partner-hero"><div><span className="eyebrow">{ui.partnerProfile} · {profile.kind==='winery'?ui.winery:ui.merchant}</span><h1>{profile.displayName}</h1><p className="lead">{content.tagline}</p><div className="partner-actions"><StateBadge state={profile.verification}/>{profile.shopUrl&&<a className="secondary-button" href={profile.shopUrl} target="_blank" rel="noreferrer">{ui.visitShop}<ExternalLink/></a>}</div>{profile.verification!=='verified'&&<small>{ui.profileDraftNotice}</small>}</div><img src={vineyardHero} alt=""/></section><section className="partner-story"><div><span>{ui.estateAuthored}</span><h2>{content.tagline}</h2><p>{content.story}</p></div><aside><ShieldCheck/><strong>{ui.editorialIntegrity}</strong><p>{ui.editorialContext}</p>{producer&&<Link to={`/wineries/${producer.id}`}>{producer.name}<ArrowRight/></Link>}</aside></section>{profile.kind==='winery'?<section className="partner-sections">{sections.map((section,index)=>{const copy=sectionSeedCopy(section,ui);return <article key={section.id}><span>{String(index+1).padStart(2,'0')} · {sectionTypeLabel(section.type,ui)}</span><h2>{copy.heading}</h2><p>{copy.body}</p>{section.type==='wines'&&producer&&<div className="partner-wines">{wines.filter(wine=>wine.producerId===producer.id).slice(0,6).map(wine=><Link key={wine.id} to={`/wines/${wine.id}`}>{wine.name}<ArrowRight/></Link>)}</div>}</article>})}</section>:<section className="studio-section"><header><span>{ui.merchantDestinations}</span><h2>{ui.offersTitle}</h2><p>{ui.offersBody}</p></header><OfferRows offers={offers}/></section>}<InfrastructureNotice/></div>
}

function useWorkspace(preferred?:BusinessWorkspace['role']){
  const all=repository.workspaces.all(demoWorkspaces);const initial=all.find(item=>item.id===localStorage.getItem('vine-atlas.business.active-workspace'))??all.find(item=>item.role===preferred)??all[0];const [workspaceId,setWorkspaceIdState]=useState(initial.id);const setWorkspaceId=(id:string)=>{setWorkspaceIdState(id);localStorage.setItem('vine-atlas.business.active-workspace',id)};return {all,workspace:all.find(item=>item.id===workspaceId)??all[0],setWorkspaceId}
}

function StudioNav({workspace}:{workspace:BusinessWorkspace}){const ui=useUiCopy();return <nav className="studio-nav"><Link to="/studio">{ui.workspace}</Link><Link to="/studio/events">{ui.eventsNav}</Link>{workspace.role==='winery'&&<Link to="/studio/site">{ui.siteComposer}</Link>}{workspace.role==='merchant'&&<><Link to="/studio/site">{ui.merchantProfile}</Link><Link to="/studio/offers">{ui.offersTitle}</Link></>}{(workspace.role==='admin'||workspace.role==='host'||workspace.role==='winery'||workspace.role==='merchant')&&<Link to="/studio/placements">{ui.placementTitle}</Link>}</nav>}
function WorkspaceSelector({all,value,onChange}:{all:BusinessWorkspace[];value:string;onChange:(id:string)=>void}){const ui=useUiCopy();return <label className="workspace-selector"><span>{ui.switchWorkspace}</span><select value={value} onChange={event=>onChange(event.target.value)}>{all.map(item=><option value={item.id} key={item.id}>{item.name} · {roleLabel(item.role,ui)}</option>)}</select><ChevronDown/></label>}
function StudioHeader({workspace,all,setWorkspaceId,title,body}:{workspace:BusinessWorkspace;all:BusinessWorkspace[];setWorkspaceId:(id:string)=>void;title:string;body:string}){const ui=useUiCopy();return <><BusinessIntro eyebrow={`${ui.studioNav} · ${roleLabel(workspace.role,ui)}`} title={title} action={<WorkspaceSelector all={all} value={workspace.id} onChange={setWorkspaceId}/>}><p>{body}</p><div className="studio-status"><StateBadge state={workspace.verification}/><StateBadge state={workspace.publishState}/><span>{ui.plan}: {planLabel(workspace.plan,ui)}</span></div></BusinessIntro><StudioNav workspace={workspace}/></>}

export function StudioHome(){
  const {all,workspace,setWorkspaceId}=useWorkspace();const ui=useUiCopy();const events=repository.events.all(demoEvents).filter(item=>item.workspaceId===workspace.id);const offers=repository.offers.all(demoOffers).filter(item=>item.workspaceId===workspace.id);const sections=repository.winerySections.all(demoWinerySections).filter(item=>item.workspaceId===workspace.id);const approvals=repository.approvals.all(demoApprovals).filter(item=>item.workspaceId===workspace.id&&item.state==='pending');const complete=workspace.checklist.filter(item=>item.complete).length
  return <div className="page business-page"><StudioHeader workspace={workspace} all={all} setWorkspaceId={setWorkspaceId} title={ui.studioTitle} body={ui.studioBody}/><section className="studio-command"><article className="onboarding-card"><div><span>{ui.onboarding}</span><strong>{complete}/{workspace.checklist.length} {ui.completed}</strong></div><div className="onboarding-progress"><i style={{width:`${complete/workspace.checklist.length*100}%`}}/></div><ul>{workspace.checklist.map(item=><li className={item.complete?'done':''} key={item.id}><span>{item.complete?<Check/>:item.id.slice(0,2).toUpperCase()}</span>{item.id.replaceAll('-',' ')}</li>)}</ul></article><div className="studio-kpis"><span>{ui.kpis}</span><div><article><strong>{events.length}</strong><small>{ui.eventsNav}</small></article><article><strong>{sections.length}</strong><small>{ui.pageSections}</small></article><article><strong>{offers.length}</strong><small>{ui.merchantDestinations}</small></article><article><strong>{approvals.length}</strong><small>{ui.pending}</small></article></div></div></section><section className="next-actions"><header><span>{ui.nextActions}</span><h2>{roleLabel(workspace.role,ui)}</h2></header><div><Link to="/studio/events"><CalendarDays/><strong>{ui.manageEvents}</strong><ArrowRight/></Link>{(workspace.role==='winery'||workspace.role==='merchant')&&<Link to="/studio/site"><Layers3/><strong>{ui.editSite}</strong><ArrowRight/></Link>}{workspace.role==='merchant'&&<Link to="/studio/offers"><Store/><strong>{ui.manageOffers}</strong><ArrowRight/></Link>}{workspace.role!=='member'&&<Link to="/studio/placements"><Sparkles/><strong>{ui.managePlacements}</strong><ArrowRight/></Link>}{workspace.role==='admin'&&<Link to="/admin"><ShieldCheck/><strong>{ui.approvalQueue}</strong><ArrowRight/></Link>}</div></section><InfrastructureNotice/></div>
}

export function StudioEvents(){
  const {all,workspace,setWorkspaceId}=useWorkspace('host');const ui=useUiCopy();const [events,setEvents]=useState(()=>repository.events.all(demoEvents));const [creating,setCreating]=useState(false);const [title,setTitle]=useState('');const [modality,setModality]=useState<EventModality>('in-person');const [visibility,setVisibility]=useState<EventVisibility>(workspace.role==='member'?'private':'public');const [startsAt,setStartsAt]=useState('2026-11-14T18:00');const [ticketType,setTicketType]=useState<'free'|'paid'>('free');const [price,setPrice]=useState('0');const managed=events.filter(item=>item.workspaceId===workspace.id)
  const create=(event:FormEvent)=>{event.preventDefault();const memberEvent=workspace.role==='member';const next:TastingEvent={id:`event-${crypto.randomUUID()}`,workspaceId:workspace.id,hostProfileId:'atlas-tasting-studio',title,summary:'',modality,visibility:memberEvent?'private':visibility,publishState:'draft',startsAt:new Date(startsAt).toISOString(),durationMinutes:90,language:'en',capacity:12,ticket:{type:memberEvent?'free':ticketType,amountMinor:!memberEvent&&ticketType==='paid'?Math.round(Number(price)*100):0,currency:'EUR',platformFeeBps:memberEvent?0:demoFeeConfiguration.ticketFeeBps},cancellationTerms:'',featuredWineIds:[],inviteCode:`VINE-${Math.random().toString(36).slice(2,6).toUpperCase()}`};const updated=[...events,next];repository.events.save(updated);setEvents(updated);setTitle('');setCreating(false)}
  const toggle=(id:string)=>{const updated=events.map(item=>item.id===id?{...item,publishState:(item.publishState==='published'?'draft':'published') as PublishState}:item);repository.events.save(updated);setEvents(updated)}
  return <div className="page business-page"><StudioHeader workspace={workspace} all={all} setWorkspaceId={setWorkspaceId} title={ui.eventManagement} body={ui.eventMgmtBody}/><div className="studio-toolbar"><p><LockNotice privateOnly={workspace.role==='member'}/></p><button className="primary-button ink" onClick={()=>setCreating(value=>!value)}><Plus/>{ui.createEvent}</button></div>{creating&&<form className="studio-form" onSubmit={create}><label>{ui.eventTitle}<input required value={title} onChange={event=>setTitle(event.target.value)}/></label><label>{ui.format}<select value={modality} onChange={event=>setModality(event.target.value as EventModality)}><option value="online">{ui.online}</option><option value="in-person">{ui.inPerson}</option><option value="hybrid">{ui.hybrid}</option></select></label><label>{ui.visibility}<select disabled={workspace.role==='member'} value={workspace.role==='member'?'private':visibility} onChange={event=>setVisibility(event.target.value as EventVisibility)}><option value="public">{ui.publicLabel}</option><option value="unlisted">{ui.unlisted}</option><option value="private">{ui.privateLabel}</option></select></label><label>{ui.dateTime}<input required type="datetime-local" value={startsAt} onChange={event=>setStartsAt(event.target.value)}/></label><label>{ui.ticketType}<select disabled={workspace.role==='member'} value={ticketType} onChange={event=>setTicketType(event.target.value as typeof ticketType)}><option value="free">{ui.free}</option><option value="paid">{ui.paid}</option></select></label>{ticketType==='paid'&&<label>{ui.ticketPrice}<input type="number" min="0" step="1" value={price} onChange={event=>setPrice(event.target.value)}/></label>}<div><button type="button" className="secondary-button" onClick={()=>setCreating(false)}>{ui.cancel}</button><button className="primary-button">{ui.saveDraft}</button></div></form>}<section className="managed-list">{managed.length?managed.map(item=>{const content=eventCopy(item,ui);return <article key={item.id}><div><StateBadge state={item.publishState}/><span>{modalityLabel(item.modality,ui)} · {item.visibility}</span></div><h2>{content.title}</h2><p>{dateTime(item.startsAt,'en')} · {item.ticket.type==='free'?ui.free:money(item.ticket.amountMinor,item.ticket.currency,'en')}</p>{item.visibility==='private'&&<small>{ui.code}: {item.inviteCode}</small>}<footer><button className="secondary-button" onClick={()=>toggle(item.id)}>{ui.publishToggle}: {item.publishState==='published'?ui.draft:ui.published}</button><Link to={`/events/${item.id}`}>{ui.previewJourney}<ArrowRight/></Link></footer></article>}):<div className="business-empty"><CalendarDays/><h2>{ui.noManagedEvents}</h2></div>}</section><InfrastructureNotice/></div>
}
function LockNotice({privateOnly}:{privateOnly:boolean}){const ui=useUiCopy();return <><ShieldCheck/>{privateOnly?ui.inviteOnlyPrivate:ui.editorialIntegrityBody}</>}

export function StudioSite(){
  const {all,workspace,setWorkspaceId}=useWorkspace('winery');const ui=useUiCopy();const [sections,setSections]=useState(()=>repository.winerySections.all(demoWinerySections));const [type,setType]=useState<WineryPageSection['type']>('story');const [heading,setHeading]=useState('');const [body,setBody]=useState('');const managed=sections.filter(item=>item.workspaceId===workspace.id).sort((a,b)=>a.order-b.order);const persist=(next:WineryPageSection[])=>{repository.winerySections.save(next);setSections(next)};const add=(event:FormEvent)=>{event.preventDefault();const next=[...sections,{id:crypto.randomUUID(),workspaceId:workspace.id,type,heading,body,visible:true,order:managed.length+1}];persist(next);setHeading('');setBody('')};const update=(id:string,change:Partial<WineryPageSection>)=>persist(sections.map(item=>item.id===id?{...item,...change}:item));const move=(id:string,direction:-1|1)=>{const local=[...managed];const index=local.findIndex(item=>item.id===id);const swap=index+direction;if(swap<0||swap>=local.length)return;[local[index],local[swap]]=[local[swap],local[index]];const order=new Map(local.map((item,i)=>[item.id,i+1]));persist(sections.map(item=>order.has(item.id)?{...item,order:order.get(item.id)!}:item))}
  return <div className="page business-page"><StudioHeader workspace={workspace} all={all} setWorkspaceId={setWorkspaceId} title={workspace.role==='merchant'?ui.merchantProfile:ui.siteComposer} body={workspace.role==='merchant'?ui.merchantStory:ui.siteComposerBody}/>{workspace.role==='merchant'?<section className="profile-editor"><Store/><div><span>{ui.merchantProfile}</span><h2>{workspace.name}</h2><p>{ui.merchantStory}</p></div><Link className="primary-button ink" to="/studio/offers">{ui.manageOffers}<ArrowRight/></Link></section>:<><form className="section-composer" onSubmit={add}><span>{ui.addSection}</span><label>{ui.sectionType}<select value={type} onChange={event=>setType(event.target.value as WineryPageSection['type'])}>{(['hero','story','vineyards','cellar','visits','team','gallery','wines','contact'] as const).map(value=><option value={value} key={value}>{sectionTypeLabel(value,ui)}</option>)}</select></label><label>{ui.heading}<input required value={heading} onChange={event=>setHeading(event.target.value)}/></label><label>{ui.sectionBody}<textarea required value={body} onChange={event=>setBody(event.target.value)}/></label><button className="primary-button"><Plus/>{ui.addSection}</button></form><section className="section-stack">{managed.map((section,index)=>{const copy=sectionSeedCopy(section,ui);return <article className={!section.visible?'is-hidden':''} key={section.id}><span className="section-handle">{String(index+1).padStart(2,'0')}</span><div><small>{sectionTypeLabel(section.type,ui)}</small><h2>{copy.heading}</h2><p>{copy.body}</p></div><div className="section-actions"><button onClick={()=>move(section.id,-1)} disabled={index===0} aria-label={ui.moveUp}>↑</button><button onClick={()=>move(section.id,1)} disabled={index===managed.length-1} aria-label={ui.moveDown}>↓</button><button onClick={()=>update(section.id,{visible:!section.visible})}>{section.visible?ui.hide:ui.show}</button><button onClick={()=>persist(sections.filter(item=>item.id!==section.id))} aria-label={ui.deleteLabel}><Trash2/></button></div></article>})}</section></>}<InfrastructureNotice/></div>
}

function stockLabel(value:MerchantOffer['stock'],ui:Ui){return value==='in-stock'?ui.inStock:value==='low'?ui.lowStock:value==='preorder'?ui.preorder:ui.outStock}
function OfferRows({offers,onToggle,onDelete}:{offers:MerchantOffer[];onToggle?:(id:string)=>void;onDelete?:(id:string)=>void}){const {locale}=useLocale();const ui=useUiCopy();return <div className="offer-list">{offers.length?offers.map(offer=>{const wine=wines.find(item=>item.id===offer.wineId);return <article key={offer.id}><div><span className={`offer-disclosure ${offer.disclosure}`}>{offer.disclosure==='affiliate'?ui.affiliate:ui.retailer}</span><StateBadge state={offer.publishState}/></div><h3>{wine?.name}</h3><p>{offer.market} · {stockLabel(offer.stock,ui)}</p><strong>{money(offer.priceMinor,offer.currency,locale)}</strong><footer>{onToggle&&<button onClick={()=>onToggle(offer.id)}>{offer.publishState==='published'?ui.deactivate:ui.activate}</button>}{onDelete&&<button onClick={()=>onDelete(offer.id)} aria-label={ui.deleteLabel}><Trash2/></button>}{!onToggle&&<a href={offer.destinationUrl} target="_blank" rel="nofollow sponsored noreferrer">{ui.externalDestination}<ExternalLink/></a>}</footer></article>}):<div className="business-empty"><Store/><h2>{ui.noOffers}</h2></div>}</div>}

export function StudioOffers(){
  const {all,workspace,setWorkspaceId}=useWorkspace('merchant');const ui=useUiCopy();const [offers,setOffers]=useState(()=>repository.offers.all(demoOffers));const [wineId,setWineId]=useState(wines[0].id);const [url,setUrl]=useState('https://');const [price,setPrice]=useState('0');const [market,setMarket]=useState('Germany');const managed=offers.filter(item=>item.workspaceId===workspace.id);const persist=(next:MerchantOffer[])=>{repository.offers.save(next);setOffers(next)};const add=(event:FormEvent)=>{event.preventDefault();persist([...offers,{id:crypto.randomUUID(),workspaceId:workspace.id,wineId,destinationUrl:url,priceMinor:Math.round(Number(price)*100),currency:'EUR',market,stock:'in-stock',disclosure:'retailer',publishState:'draft'}]);setUrl('https://');setPrice('0')};const toggle=(id:string)=>persist(offers.map(item=>item.id===id?{...item,publishState:(item.publishState==='published'?'draft':'published') as PublishState}:item))
  return <div className="page business-page"><StudioHeader workspace={workspace} all={all} setWorkspaceId={setWorkspaceId} title={ui.offersTitle} body={ui.offersBody}/><form className="offer-composer" onSubmit={add}><label>{ui.selectWine}<select value={wineId} onChange={event=>setWineId(event.target.value)}>{wines.map(wine=><option value={wine.id} key={wine.id}>{wine.name} · {producers.find(item=>item.id===wine.producerId)?.name}</option>)}</select></label><label>{ui.destinationUrl}<input type="url" required value={url} onChange={event=>setUrl(event.target.value)}/></label><label>{ui.ticketPrice}<input type="number" min="0" step="0.01" required value={price} onChange={event=>setPrice(event.target.value)}/></label><label>{ui.market}<input required value={market} onChange={event=>setMarket(event.target.value)}/></label><button className="primary-button"><Plus/>{ui.addOffer}</button></form><OfferRows offers={managed} onToggle={toggle} onDelete={id=>persist(offers.filter(item=>item.id!==id))}/><InfrastructureNotice/></div>
}

export function StudioPlacements(){
  const {all,workspace,setWorkspaceId}=useWorkspace('admin');const ui=useUiCopy();const [placements,setPlacements]=useState(()=>repository.placements.all(demoPlacements));const managed=workspace.role==='admin'?placements:placements.filter(item=>item.workspaceId===workspace.id);const persist=(next:PromotionalPlacement[])=>{repository.placements.save(next);setPlacements(next)};const update=(id:string,change:Partial<PromotionalPlacement>)=>persist(placements.map(item=>item.id===id?{...item,...change}:item))
  return <div className="page business-page"><StudioHeader workspace={workspace} all={all} setWorkspaceId={setWorkspaceId} title={ui.placementTitle} body={ui.placementBody}/><section className="placement-list">{managed.map(item=>{const profile=demoPartnerProfiles.find(profile=>profile.id===item.partnerProfileId);return <article key={item.id}><header><span className={`placement-disclosure ${item.disclosure}`}>{item.disclosure==='featured'?ui.featured:ui.sponsored}</span><strong>{profile?.displayName}</strong><button className={item.enabled?'active':''} onClick={()=>update(item.id,{enabled:!item.enabled})}>{item.enabled?ui.enabled:ui.disabled}</button></header><div><label>{ui.surface}<select value={item.surface} onChange={event=>update(item.id,{surface:event.target.value as PromotionalPlacement['surface']})}><option value="home">{ui.homeLabel}</option><option value="map">{ui.worldAtlas}</option><option value="region">{ui.region}</option><option value="search">{ui.search}</option></select></label><label>{ui.starts}<input type="date" value={item.startsAt} onChange={event=>update(item.id,{startsAt:event.target.value})}/></label><label>{ui.ends}<input type="date" value={item.endsAt} onChange={event=>update(item.id,{endsAt:event.target.value})}/></label><label>{ui.priority}<input type="number" min="1" max="9" value={item.priority} onChange={event=>update(item.id,{priority:Number(event.target.value)})}/></label></div></article>})}</section><aside className="integrity-panel"><ShieldCheck/><div><span>{ui.editorialIntegrity}</span><h2>{ui.editorialIntegrityBody}</h2></div></aside></div>
}

export function BusinessAdminPanel(){
  const ui=useUiCopy();const [approvals,setApprovals]=useState(()=>repository.approvals.all(demoApprovals));const [fees]=useState(()=>repository.feeConfiguration.get(demoFeeConfiguration));const update=(id:string,state:'approved'|'rejected')=>{const next=approvals.map(item=>item.id===id?{...item,state}:item);repository.approvals.save(next);setApprovals(next)}
  return <section className="business-admin"><header><div><span>{ui.approvalQueue}</span><h2>{ui.approvalBody}</h2></div><strong>{approvals.filter(item=>item.state==='pending').length} {ui.pending}</strong></header><div className="approval-grid"><div className="approval-list">{approvals.map(item=><article key={item.id}><div><small>{approvalKindLabel(item.kind,ui)}</small><h3>{item.title}</h3><StateBadge state={item.state}/></div>{item.state==='pending'&&<footer><button onClick={()=>update(item.id,'rejected')}><X/>{ui.reject}</button><button onClick={()=>update(item.id,'approved')}><Check/>{ui.approve}</button></footer>}</article>)}</div><aside><span>{ui.commercialLayer}</span><h3>{ui.configurable}</h3><dl><div><dt>{ui.recurringPlans}</dt><dd>{fees.recurringPartnerPlans?ui.enabled:ui.disabled}</dd></div><div><dt>{ui.ticketFees}</dt><dd>{fees.ticketFeeBps/100}%</dd></div><div><dt>{ui.affiliateLinks}</dt><dd>{fees.merchantAffiliateLinks?ui.enabled:ui.disabled}</dd></div><div><dt>{ui.paymentFuture}</dt><dd>{ui.notConnected}</dd></div></dl><p>{ui.editorialIntegrityBody}</p></aside></div></section>
}

export function FeaturedBusinessHome(){const ui=useUiCopy();return <section className="featured-business-home"><div><span className="placement-disclosure featured">{ui.featured}</span><small>{ui.professionalHost}</small><h2>{ui.homePlacementTitle}</h2><p>{ui.homePlacementBody}</p><div><Link to="/events" className="primary-button">{ui.viewEvents}<ArrowRight/></Link><Link to="/hosts/atlas-tasting-studio">{ui.hostProfile}<ArrowRight/></Link></div></div><img src={tastingStill} alt=""/></section>}

export function AtlasCommercialPlacements(){const ui=useUiCopy();const today=new Date().toISOString().slice(0,10);const placements=repository.placements.all(demoPlacements).filter(item=>item.enabled&&item.surface==='map'&&item.startsAt<=today&&item.endsAt>=today);if(!placements.length)return null;return <div className="atlas-commercial-overlay">{placements.map(item=>{const profile=demoPartnerProfiles.find(profile=>profile.id===item.partnerProfileId);return profile?<Link key={item.id} to={`/partners/${profile.id}`}><span className={`placement-disclosure ${item.disclosure}`}>{item.disclosure==='featured'?ui.featured:ui.sponsored}</span><strong>{profile.displayName}</strong><ArrowRight/></Link>:null})}</div>}

export function ProducerBusinessLayer({producerId}:{producerId:string}){const ui=useUiCopy();const profile=repository.partnerProfiles.all(demoPartnerProfiles).find(item=>item.producerId===producerId);if(!profile)return null;return <aside className="partner-context-strip"><div><span className="placement-disclosure featured">{ui.estateAuthored}</span><strong>{ui.partnerProfile}</strong><p>{ui.editorialContext}</p></div><Link className="primary-button ink" to={`/partners/${profile.id}`}>{ui.publicProfile}<ArrowRight/></Link></aside>}

export function WineMerchantOffers({wineId}:{wineId:string}){const ui=useUiCopy();const offers=repository.offers.all(demoOffers).filter(item=>item.wineId===wineId);if(!offers.length)return null;return <section className="wine-merchant-layer"><header><span className="eyebrow">{ui.commercialLayer}</span><h2>{ui.offersTitle}</h2><p>{ui.offersBody}</p></header><OfferRows offers={offers}/></section>}
