import { useMemo, useState, type FormEvent } from 'react'
import { Link } from 'react-router-dom'
import { Archive, Camera, Check, ChevronDown, ChevronUp, CircleDollarSign, Clock3, Grape, ImagePlus, MapPin, Minus, NotebookPen, Plus, Search, SlidersHorizontal, Sparkles, Trash2, Wine, X } from 'lucide-react'
import { aromaContent, countryLabel } from './localizedContent'
import { aromas, grapes, producers, regions, wines } from './data/catalog'
import { repository } from './data/repository'
import { prepareBottlePhoto } from './lib/image'
import { useLocale, type Locale } from './i18n'
import type { CellarItem, CellarTastingNote } from './types'
import bottleForms from './assets/wine-bottle-forms.jpg'

type CellarState = CellarItem['state']

const cellarCopy: Record<Locale, {
  eyebrow:string; title:string; intro:string; add:string; search:string; all:string; bottles:string; wishlist:string; noted:string; emptyTitle:string; emptyBody:string;
  owned:string; tasted:string; finished:string; details:string; closeDetails:string; remove:string; confirmRemove:string; quantity:string; location:string; vintage:string; bottleSize:string;
  purchaseDate:string; purchasePrice:string; currency:string; source:string; drinkWindow:string; drinkFrom:string; drinkUntil:string; occasion:string; saveDetails:string; saved:string;
  notes:string; addNote:string; appearance:string; aromas:string; palate:string; finish:string; reflection:string; acidity:string; tannin:string; body:string; rating:string; saveNote:string;
  noNotes:string; fromAtlas:string; ownEntry:string; wine:string; wineName:string; producer:string; region:string; collection:string; photo:string; photoBody:string; choosePhoto:string;
  changePhoto:string; removePhoto:string; preparing:string; photoError:string; saveBottle:string; nonVintage:string; bottleStudy:string; bottleStudyBody:string; latestNote:string;
  light:string; medium:string; full:string; short:string; persistent:string; clear:string; pale:string; deep:string; homeCellar:string; addSuccess:string;
}> = {
  en:{eyebrow:'Personal collection',title:'A cellar built from memories',intro:'Keep bottles, drinking windows and purchase details together with the sensory notes that made a wine worth remembering.',add:'Add a bottle',search:'Search wine, producer, region or vintage',all:'All',bottles:'bottles',wishlist:'wish list',noted:'with notes',emptyTitle:'No bottles in this view',emptyBody:'Change the filter or add the first bottle to begin your cellar.',owned:'Owned',tasted:'Tasted',finished:'Finished',details:'Open bottle record',closeDetails:'Close bottle record',remove:'Remove',confirmRemove:'Remove permanently?',quantity:'Quantity',location:'Storage location',vintage:'Vintage',bottleSize:'Bottle size',purchaseDate:'Purchase date',purchasePrice:'Purchase price',currency:'Currency',source:'Bought from',drinkWindow:'Drinking window',drinkFrom:'From',drinkUntil:'Until',occasion:'Occasion or memory',saveDetails:'Save bottle details',saved:'Saved',notes:'Tasting notes',addNote:'Add a structured note',appearance:'Appearance',aromas:'Aromas',palate:'Palate',finish:'Finish',reflection:'Conclusion and memory',acidity:'Acidity',tannin:'Tannin',body:'Body',rating:'Rating',saveNote:'Save tasting note',noNotes:'No tasting note yet. Record the wine as it is today; the next bottle may tell a different story.',fromAtlas:'From the atlas',ownEntry:'My own entry',wine:'Wine',wineName:'Wine name',producer:'Producer',region:'Region',collection:'Collection',photo:'Bottle photo',photoBody:'Use the camera or choose an image. It is resized and kept privately in this browser.',choosePhoto:'Choose photo',changePhoto:'Change photo',removePhoto:'Remove photo',preparing:'Preparing photo…',photoError:'This image could not be prepared.',saveBottle:'Save to cellar',nonVintage:'NV',bottleStudy:'Why bottle shapes differ',bottleStudyBody:'Shoulders, glass weight and bottle pressure began as practical choices. Shape can suggest tradition, but it never proves quality.',latestNote:'Latest note',light:'Light',medium:'Medium',full:'Full',short:'Short',persistent:'Persistent',clear:'Clear',pale:'Pale',deep:'Deep',homeCellar:'Home cellar',addSuccess:'Bottle added to your cellar.'},
  de:{eyebrow:'Persönliche Sammlung',title:'Ein Keller aus Erinnerungen',intro:'Bewahre Flaschen, Trinkfenster und Einkaufsdetails zusammen mit den sensorischen Notizen auf, die einen Wein erinnerungswürdig gemacht haben.',add:'Flasche hinzufügen',search:'Wein, Winzer, Region oder Jahrgang suchen',all:'Alle',bottles:'Flaschen',wishlist:'Wunschliste',noted:'mit Notizen',emptyTitle:'Keine Flaschen in dieser Ansicht',emptyBody:'Ändere den Filter oder lege die erste Flasche in deinen Keller.',owned:'Im Keller',tasted:'Verkostet',finished:'Getrunken',details:'Flaschendetails öffnen',closeDetails:'Flaschendetails schließen',remove:'Entfernen',confirmRemove:'Dauerhaft entfernen?',quantity:'Anzahl',location:'Lagerort',vintage:'Jahrgang',bottleSize:'Flaschengröße',purchaseDate:'Kaufdatum',purchasePrice:'Kaufpreis',currency:'Währung',source:'Gekauft bei',drinkWindow:'Trinkfenster',drinkFrom:'Von',drinkUntil:'Bis',occasion:'Anlass oder Erinnerung',saveDetails:'Flaschendetails speichern',saved:'Gespeichert',notes:'Verkostungsnotizen',addNote:'Strukturierte Notiz anlegen',appearance:'Aussehen',aromas:'Aromen',palate:'Gaumen',finish:'Abgang',reflection:'Fazit und Erinnerung',acidity:'Säure',tannin:'Tannin',body:'Körper',rating:'Bewertung',saveNote:'Verkostungsnotiz speichern',noNotes:'Noch keine Verkostungsnotiz. Halte den Wein so fest, wie er heute wirkt; die nächste Flasche kann eine neue Geschichte erzählen.',fromAtlas:'Aus dem Atlas',ownEntry:'Eigener Eintrag',wine:'Wein',wineName:'Weinname',producer:'Weingut',region:'Region',collection:'Sammlung',photo:'Flaschenfoto',photoBody:'Nutze die Kamera oder wähle ein Bild. Es wird verkleinert und privat in diesem Browser gespeichert.',choosePhoto:'Foto wählen',changePhoto:'Foto ändern',removePhoto:'Foto entfernen',preparing:'Foto wird vorbereitet…',photoError:'Dieses Bild konnte nicht vorbereitet werden.',saveBottle:'Im Keller speichern',nonVintage:'NV',bottleStudy:'Warum Flaschenformen verschieden sind',bottleStudyBody:'Schultern, Glasgewicht und Druckfestigkeit entstanden aus praktischen Entscheidungen. Eine Form kann Tradition andeuten, beweist aber nie Qualität.',latestNote:'Neueste Notiz',light:'Leicht',medium:'Mittel',full:'Kräftig',short:'Kurz',persistent:'Anhaltend',clear:'Klar',pale:'Hell',deep:'Tief',homeCellar:'Hauskeller',addSuccess:'Flasche wurde deinem Keller hinzugefügt.'},
  fr:{eyebrow:'Collection personnelle',title:'Une cave faite de souvenirs',intro:'Réunissez bouteilles, fenêtres de dégustation, achats et notes sensorielles qui rendent un vin mémorable.',add:'Ajouter une bouteille',search:'Chercher vin, domaine, région ou millésime',all:'Tout',bottles:'bouteilles',wishlist:'liste de souhaits',noted:'avec notes',emptyTitle:'Aucune bouteille dans cette vue',emptyBody:'Changez le filtre ou ajoutez la première bouteille de votre cave.',owned:'En cave',tasted:'Dégusté',finished:'Bu',details:'Ouvrir la fiche bouteille',closeDetails:'Fermer la fiche bouteille',remove:'Retirer',confirmRemove:'Retirer définitivement ?',quantity:'Quantité',location:'Lieu de stockage',vintage:'Millésime',bottleSize:'Format',purchaseDate:'Date d’achat',purchasePrice:'Prix d’achat',currency:'Devise',source:'Acheté chez',drinkWindow:'Fenêtre de dégustation',drinkFrom:'De',drinkUntil:'À',occasion:'Occasion ou souvenir',saveDetails:'Enregistrer les détails',saved:'Enregistré',notes:'Notes de dégustation',addNote:'Ajouter une note structurée',appearance:'Robe',aromas:'Arômes',palate:'Bouche',finish:'Finale',reflection:'Conclusion et souvenir',acidity:'Acidité',tannin:'Tanins',body:'Corps',rating:'Note',saveNote:'Enregistrer la note',noNotes:'Aucune note pour le moment. Décrivez le vin aujourd’hui ; la prochaine bouteille racontera peut-être autre chose.',fromAtlas:'Depuis l’atlas',ownEntry:'Mon entrée',wine:'Vin',wineName:'Nom du vin',producer:'Domaine',region:'Région',collection:'Collection',photo:'Photo de la bouteille',photoBody:'Utilisez l’appareil ou choisissez une image. Elle sera réduite et conservée dans ce navigateur.',choosePhoto:'Choisir une photo',changePhoto:'Changer la photo',removePhoto:'Retirer la photo',preparing:'Préparation de la photo…',photoError:'Cette image n’a pas pu être préparée.',saveBottle:'Enregistrer en cave',nonVintage:'NM',bottleStudy:'Pourquoi les formes diffèrent',bottleStudyBody:'Épaules, poids du verre et résistance à la pression viennent de choix pratiques. La forme évoque une tradition, jamais une garantie de qualité.',latestNote:'Dernière note',light:'Léger',medium:'Moyen',full:'Plein',short:'Courte',persistent:'Persistante',clear:'Limpide',pale:'Pâle',deep:'Profonde',homeCellar:'Cave personnelle',addSuccess:'Bouteille ajoutée à votre cave.'},
  es:{eyebrow:'Colección personal',title:'Una bodega hecha de recuerdos',intro:'Guarda botellas, ventanas de consumo y detalles de compra junto a las notas sensoriales que hicieron memorable un vino.',add:'Añadir una botella',search:'Buscar vino, bodega, región o añada',all:'Todo',bottles:'botellas',wishlist:'lista de deseos',noted:'con notas',emptyTitle:'No hay botellas en esta vista',emptyBody:'Cambia el filtro o añade la primera botella a tu bodega.',owned:'En bodega',tasted:'Catado',finished:'Terminado',details:'Abrir ficha de botella',closeDetails:'Cerrar ficha de botella',remove:'Eliminar',confirmRemove:'¿Eliminar definitivamente?',quantity:'Cantidad',location:'Lugar de guarda',vintage:'Añada',bottleSize:'Tamaño de botella',purchaseDate:'Fecha de compra',purchasePrice:'Precio de compra',currency:'Moneda',source:'Comprado en',drinkWindow:'Ventana de consumo',drinkFrom:'Desde',drinkUntil:'Hasta',occasion:'Ocasión o recuerdo',saveDetails:'Guardar detalles',saved:'Guardado',notes:'Notas de cata',addNote:'Añadir nota estructurada',appearance:'Aspecto',aromas:'Aromas',palate:'Boca',finish:'Final',reflection:'Conclusión y recuerdo',acidity:'Acidez',tannin:'Tanino',body:'Cuerpo',rating:'Valoración',saveNote:'Guardar nota de cata',noNotes:'Todavía no hay una nota. Describe el vino hoy; la próxima botella puede contar una historia distinta.',fromAtlas:'Desde el atlas',ownEntry:'Entrada propia',wine:'Vino',wineName:'Nombre del vino',producer:'Bodega',region:'Región',collection:'Colección',photo:'Foto de la botella',photoBody:'Usa la cámara o elige una imagen. Se reduce y se guarda de forma privada en este navegador.',choosePhoto:'Elegir foto',changePhoto:'Cambiar foto',removePhoto:'Quitar foto',preparing:'Preparando foto…',photoError:'No se pudo preparar esta imagen.',saveBottle:'Guardar en bodega',nonVintage:'SN',bottleStudy:'Por qué cambian las formas',bottleStudyBody:'Hombros, peso del vidrio y resistencia a la presión nacieron de decisiones prácticas. La forma sugiere tradición, nunca garantiza calidad.',latestNote:'Última nota',light:'Ligero',medium:'Medio',full:'Pleno',short:'Corto',persistent:'Persistente',clear:'Limpio',pale:'Pálido',deep:'Profundo',homeCellar:'Bodega de casa',addSuccess:'Botella añadida a tu bodega.'},
}

const stateOrder: CellarState[]=['owned','wishlist','tasted','finished']

function BottlePortrait({item}:{item:CellarItem}){
  const wine=wines.find(entry=>entry.id===item.wineId)
  const vintage=item.vintage??wine?.vintage
  return <div className={`bottle-portrait style-${wine?.style??'red'}`}>
    {item.imageDataUrl?<img src={item.imageDataUrl} alt=""/>:<div className="bottle-object" aria-hidden="true"><i/><b><span>{vintage??'NV'}</span><em>{(wine?.name??item.customName??'Vine Atlas').slice(0,18)}</em></b></div>}
  </div>
}

export function CellarExperience(){
  const {locale}=useLocale(); const c=cellarCopy[locale]
  const [items,setItems]=useState<CellarItem[]>(()=>repository.cellar.all())
  const [filter,setFilter]=useState<'all'|CellarState>('all'); const [query,setQuery]=useState('')
  const [expanded,setExpanded]=useState<string>(); const [deleting,setDeleting]=useState<string>(); const [addOpen,setAddOpen]=useState(false); const [toast,setToast]=useState('')
  function persist(next:CellarItem[]){setItems(next);repository.cellar.save(next)}
  const filtered=useMemo(()=>items.filter(item=>{
    if(filter!=='all'&&item.state!==filter)return false
    const wine=wines.find(entry=>entry.id===item.wineId),producer=wine?producers.find(entry=>entry.id===wine.producerId):undefined,region=wine?regions.find(entry=>entry.id===wine.regionId):undefined
    return `${wine?.name??item.customName??''} ${producer?.name??item.producer??''} ${region?.name??item.region??''} ${item.vintage??wine?.vintage??''}`.toLowerCase().includes(query.toLowerCase())
  }),[items,filter,query])
  function updateItem(id:string,patch:Partial<CellarItem>){persist(items.map(item=>item.id===id?{...item,...patch}:item))}
  function removeItem(id:string){if(deleting!==id){setDeleting(id);return}persist(items.filter(item=>item.id!==id));setDeleting(undefined);setExpanded(undefined);setToast('')}
  return <main className="page cellar-experience">
    <header className="cellar-experience-hero">
      <div><span className="eyebrow">{c.eyebrow}</span><h1>{c.title}</h1><p>{c.intro}</p><button className="primary-button" onClick={()=>setAddOpen(true)}><Plus/>{c.add}</button></div>
      <figure><img src={bottleForms} alt=""/><figcaption><strong>{c.bottleStudy}</strong><span>{c.bottleStudyBody}</span></figcaption></figure>
    </header>
    <section className="cellar-metrics">
      <article><Wine/><strong>{items.reduce((sum,item)=>sum+item.quantity,0)}</strong><span>{c.bottles}</span></article>
      <article><Sparkles/><strong>{items.filter(item=>item.state==='wishlist').length}</strong><span>{c.wishlist}</span></article>
      <article><NotebookPen/><strong>{items.filter(item=>item.notes?.length).length}</strong><span>{c.noted}</span></article>
    </section>
    <div className="cellar-commandbar">
      <label className="search-field"><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder={c.search}/></label>
      <div><SlidersHorizontal/>{(['all',...stateOrder] as const).map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value==='all'?c.all:value==='wishlist'?c.wishlist:c[value]}</button>)}</div>
    </div>
    {toast&&<div className="cellar-toast"><Check/>{toast}<button onClick={()=>setToast('')}><X/></button></div>}
    {filtered.length?<section className="cellar-collection-grid">{filtered.map(item=>{
      const wine=wines.find(entry=>entry.id===item.wineId),producer=wine?producers.find(entry=>entry.id===wine.producerId):undefined,region=wine?regions.find(entry=>entry.id===wine.regionId):undefined
      const latest=item.notes?.at(-1)
      return <article className={expanded===item.id?'cellar-record expanded':'cellar-record'} key={item.id}>
        <BottlePortrait item={item}/>
        <div className="cellar-record-copy"><div className="record-kicker"><span>{item.state==='wishlist'?c.wishlist:c[item.state]}</span><em>{item.vintage??wine?.vintage??c.nonVintage}</em></div>
          <h2>{wine?.name??item.customName}</h2><p>{producer?.name??item.producer}</p>
          <div className="record-place"><MapPin/>{region?<Link to={`/regions/${region.id}`}>{region.name} · {countryLabel(region.country,locale)}</Link>:item.region}</div>
          {latest&&<div className="latest-note"><span>{c.latestNote}</span><strong>{'★'.repeat(latest.rating)}{'☆'.repeat(5-latest.rating)}</strong><p>{latest.reflection||latest.palate}</p></div>}
          <div className="record-actions"><div><button aria-label="-" onClick={()=>updateItem(item.id,{quantity:Math.max(0,item.quantity-1)})}><Minus/></button><span>{item.quantity}</span><button aria-label="+" onClick={()=>updateItem(item.id,{quantity:item.quantity+1})}><Plus/></button></div>
            <button className="text-button" onClick={()=>setExpanded(expanded===item.id?undefined:item.id)}>{expanded===item.id?<><ChevronUp/>{c.closeDetails}</>:<><ChevronDown/>{c.details}</>}</button>
          </div>
        </div>
        {expanded===item.id&&<BottleRecord item={item} c={c} locale={locale} onUpdate={patch=>updateItem(item.id,patch)} onRemove={()=>removeItem(item.id)} confirmRemove={deleting===item.id}/>} 
      </article>})}</section>:<section className="cellar-empty"><Archive/><h2>{c.emptyTitle}</h2><p>{c.emptyBody}</p><button className="primary-button ink" onClick={()=>setAddOpen(true)}>{c.add}</button></section>}
    {addOpen&&<AddBottleSheet c={c} onClose={()=>setAddOpen(false)} onSave={item=>{persist([...items,item]);setAddOpen(false);setToast(c.addSuccess);window.setTimeout(()=>setToast(''),3600)}}/>}
  </main>
}

function BottleRecord({item,c,locale,onUpdate,onRemove,confirmRemove}:{item:CellarItem;c:typeof cellarCopy.en;locale:Locale;onUpdate:(patch:Partial<CellarItem>)=>void;onRemove:()=>void;confirmRemove:boolean}){
  const wine=wines.find(entry=>entry.id===item.wineId)
  const [saved,setSaved]=useState(false); const [aromaIds,setAromaIds]=useState<string[]>([])
  const [note,setNote]=useState({appearance:c.clear,palate:'',finish:'',reflection:'',acidity:3,tannin:wine?.style==='red'?3:1,body:3,rating:4})
  const availableAromas=wine?aromas.filter(aroma=>wine.aromaIds.includes(aroma.id)):aromas.slice(0,20)
  function saveMeta(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);onUpdate({vintage:Number(data.get('vintage'))||undefined,bottleSizeMl:Number(data.get('bottleSizeMl'))||750,location:String(data.get('location')||''),purchaseDate:String(data.get('purchaseDate')||''),purchasePrice:Number(data.get('purchasePrice'))||undefined,currency:String(data.get('currency')||'EUR') as CellarItem['currency'],purchaseSource:String(data.get('purchaseSource')||''),drinkFrom:Number(data.get('drinkFrom'))||undefined,drinkUntil:Number(data.get('drinkUntil'))||undefined,occasion:String(data.get('occasion')||'')});setSaved(true)}
  function saveNote(){const entry:CellarTastingNote={id:crypto.randomUUID(),...note,aromaIds,createdAt:new Date().toISOString()};onUpdate({notes:[...(item.notes??[]),entry],rating:entry.rating,state:item.state==='wishlist'?'tasted':item.state});setAromaIds([]);setNote({...note,palate:'',finish:'',reflection:''})}
  return <div className="bottle-record-panel">
    <form className="bottle-metadata-form" onSubmit={saveMeta}><div className="panel-heading"><div><span className="eyebrow">{c.details}</span><h3>{c.drinkWindow}</h3></div><Clock3/></div>
      <div className="metadata-grid"><label>{c.vintage}<input name="vintage" type="number" min="1800" max="2100" defaultValue={item.vintage??wine?.vintage??''}/></label><label>{c.bottleSize}<select name="bottleSizeMl" defaultValue={item.bottleSizeMl??750}><option value="375">375 ml</option><option value="750">750 ml</option><option value="1500">1.5 l</option><option value="3000">3 l</option></select></label><label>{c.location}<input name="location" defaultValue={item.location}/></label><label>{c.purchaseDate}<input name="purchaseDate" type="date" defaultValue={item.purchaseDate}/></label><label>{c.purchasePrice}<input name="purchasePrice" type="number" min="0" step="0.01" defaultValue={item.purchasePrice}/></label><label>{c.currency}<select name="currency" defaultValue={item.currency??'EUR'}>{['EUR','USD','GBP','CHF'].map(value=><option key={value}>{value}</option>)}</select></label><label>{c.source}<input name="purchaseSource" defaultValue={item.purchaseSource}/></label><label>{c.drinkFrom}<input name="drinkFrom" type="number" min="1900" max="2200" defaultValue={item.drinkFrom}/></label><label>{c.drinkUntil}<input name="drinkUntil" type="number" min="1900" max="2200" defaultValue={item.drinkUntil}/></label><label className="wide">{c.occasion}<textarea name="occasion" defaultValue={item.occasion}/></label></div>
      <button className="secondary-button">{saved?<><Check/>{c.saved}</>:c.saveDetails}</button>
    </form>
    <section className="cellar-note-studio"><div className="panel-heading"><div><span className="eyebrow">{c.notes}</span><h3>{c.addNote}</h3></div><NotebookPen/></div>
      <label>{c.appearance}<select value={note.appearance} onChange={event=>setNote({...note,appearance:event.target.value})}><option>{c.clear}</option><option>{c.pale}</option><option>{c.deep}</option></select></label>
      <div><span className="field-label">{c.aromas}</span><div className="cellar-aroma-chips">{availableAromas.map(aroma=><button type="button" key={aroma.id} className={aromaIds.includes(aroma.id)?'active':''} onClick={()=>setAromaIds(values=>values.includes(aroma.id)?values.filter(id=>id!==aroma.id):[...values,aroma.id])}>{aromaContent(aroma,locale).name}</button>)}</div></div>
      <div className="note-sliders">{(['acidity','tannin','body'] as const).map(key=><label key={key}><span>{c[key]}</span><input type="range" min="1" max="5" value={note[key]} onChange={event=>setNote({...note,[key]:Number(event.target.value)})}/><b>{note[key]}/5</b></label>)}</div>
      <div className="note-text-grid"><label>{c.palate}<textarea value={note.palate} onChange={event=>setNote({...note,palate:event.target.value})}/></label><label>{c.finish}<textarea value={note.finish} onChange={event=>setNote({...note,finish:event.target.value})}/></label><label className="wide">{c.reflection}<textarea value={note.reflection} onChange={event=>setNote({...note,reflection:event.target.value})}/></label></div>
      <label className="rating-field">{c.rating}<span>{[1,2,3,4,5].map(value=><button type="button" key={value} className={value<=note.rating?'active':''} onClick={()=>setNote({...note,rating:value})}>★</button>)}</span></label>
      <button type="button" className="primary-button" onClick={saveNote}><NotebookPen/>{c.saveNote}</button>
      <div className="note-history">{item.notes?.length?item.notes.slice().reverse().map(entry=><article key={entry.id}><header><time>{new Intl.DateTimeFormat(locale,{dateStyle:'medium'}).format(new Date(entry.createdAt))}</time><strong>{'★'.repeat(entry.rating)}{'☆'.repeat(5-entry.rating)}</strong></header><div>{entry.aromaIds.map(id=>{const aroma=aromas.find(value=>value.id===id);return aroma?<span key={id}>{aromaContent(aroma,locale).name}</span>:null})}</div><p>{entry.palate}</p><small>{entry.finish}</small><blockquote>{entry.reflection}</blockquote></article>):<p>{c.noNotes}</p>}</div>
    </section>
    <button className={confirmRemove?'danger-button confirm':'danger-button'} onClick={onRemove}><Trash2/>{confirmRemove?c.confirmRemove:c.remove}</button>
  </div>
}

function AddBottleSheet({c,onClose,onSave}:{c:typeof cellarCopy.en;onClose:()=>void;onSave:(item:CellarItem)=>void}){
  const [catalogue,setCatalogue]=useState(true);const [wineId,setWineId]=useState(wines[0].id);const [state,setState]=useState<CellarState>('owned');const [imageDataUrl,setImageDataUrl]=useState<string>();const [preparing,setPreparing]=useState(false);const [error,setError]=useState('')
  async function chooseImage(file?:File){if(!file)return;setPreparing(true);setError('');try{setImageDataUrl(await prepareBottlePhoto(file))}catch{setError(c.photoError)}finally{setPreparing(false)}}
  function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=new FormData(event.currentTarget);onSave({id:crypto.randomUUID(),...(catalogue?{wineId}:{customName:String(data.get('customName')||''),producer:String(data.get('producer')||''),region:String(data.get('region')||'')}),state,quantity:Number(data.get('quantity'))||1,location:String(data.get('location')||c.homeCellar),vintage:Number(data.get('vintage'))||undefined,bottleSizeMl:Number(data.get('bottleSizeMl'))||750,purchaseDate:String(data.get('purchaseDate')||''),purchasePrice:Number(data.get('purchasePrice'))||undefined,currency:String(data.get('currency')||'EUR') as CellarItem['currency'],purchaseSource:String(data.get('purchaseSource')||''),drinkFrom:Number(data.get('drinkFrom'))||undefined,drinkUntil:Number(data.get('drinkUntil'))||undefined,occasion:String(data.get('occasion')||''),imageDataUrl,notes:[]})}
  return <div className="modal-backdrop" onMouseDown={event=>{if(event.currentTarget===event.target)onClose()}}><form className="sheet cellar-add-sheet" onSubmit={submit}><button type="button" className="sheet-close" onClick={onClose}><X/></button><span className="eyebrow">{c.eyebrow}</span><h2>{c.add}</h2>
    <div className="bottle-photo-field"><div className={imageDataUrl?'photo-preview has-photo':'photo-preview'}>{imageDataUrl?<img src={imageDataUrl} alt=""/>:<Camera/>}</div><div><strong>{c.photo}</strong><p>{c.photoBody}</p><label className="secondary-button"><ImagePlus/>{preparing?c.preparing:imageDataUrl?c.changePhoto:c.choosePhoto}<input type="file" accept="image/*" capture="environment" onChange={event=>chooseImage(event.target.files?.[0])}/></label>{imageDataUrl&&<button type="button" className="text-button" onClick={()=>setImageDataUrl(undefined)}>{c.removePhoto}</button>}{error&&<span className="form-error">{error}</span>}</div></div>
    <div className="segmented"><button type="button" className={catalogue?'active':''} onClick={()=>setCatalogue(true)}>{c.fromAtlas}</button><button type="button" className={!catalogue?'active':''} onClick={()=>setCatalogue(false)}>{c.ownEntry}</button></div>
    {catalogue?<label>{c.wine}<select value={wineId} onChange={event=>setWineId(event.target.value)}>{wines.map(wine=><option value={wine.id} key={wine.id}>{wine.name} · {wine.vintage??c.nonVintage}</option>)}</select></label>:<div className="metadata-grid"><label>{c.wineName}<input required name="customName"/></label><label>{c.producer}<input name="producer"/></label><label>{c.region}<input name="region"/></label></div>}
    <div className="metadata-grid"><label>{c.collection}<select value={state} onChange={event=>setState(event.target.value as CellarState)}><option value="owned">{c.owned}</option><option value="wishlist">{c.wishlist}</option><option value="tasted">{c.tasted}</option><option value="finished">{c.finished}</option></select></label><label>{c.quantity}<input name="quantity" type="number" min="1" defaultValue="1"/></label><label>{c.vintage}<input name="vintage" type="number" min="1800" max="2100"/></label><label>{c.bottleSize}<select name="bottleSizeMl" defaultValue="750"><option value="375">375 ml</option><option value="750">750 ml</option><option value="1500">1.5 l</option><option value="3000">3 l</option></select></label><label>{c.location}<input name="location" defaultValue={c.homeCellar}/></label><label>{c.purchaseDate}<input name="purchaseDate" type="date"/></label><label>{c.purchasePrice}<input name="purchasePrice" type="number" step="0.01" min="0"/></label><label>{c.currency}<select name="currency"><option>EUR</option><option>USD</option><option>GBP</option><option>CHF</option></select></label><label>{c.source}<input name="purchaseSource"/></label><label>{c.drinkFrom}<input name="drinkFrom" type="number"/></label><label>{c.drinkUntil}<input name="drinkUntil" type="number"/></label><label className="wide">{c.occasion}<textarea name="occasion"/></label></div>
    <button className="primary-button"><Wine/>{c.saveBottle}</button>
  </form></div>
}
