import { createContext, useContext, useMemo, useState, type ReactNode } from "react";

export type Locale = "en" | "de" | "fr" | "es";

const en = {
  home: "Home", atlas: "Atlas", tastings: "Tastings", cellar: "Cellar", profile: "Profile",
  learn: "Learn", aromas: "Aromas", admin: "Admin", search: "Search the world of wine",
  explore: "Explore the atlas", viewRegion: "Open region", addCellar: "Add to cellar",
  join: "Join tasting", save: "Save", cancel: "Cancel", signIn: "Sign in", signOut: "Sign out",
  language: "Language", settings: "Settings", openMenu: "Open menu", close: "Close", back: "Back",
  all: "All", regions: "Regions", grapes: "Grapes", producers: "Producers", wines: "Wines",
  notes: "Notes", rating: "Your rating", owned: "Owned", wishlist: "Wishlist", tasted: "Tasted",
  finished: "Finished", quantity: "Quantity", location: "Location", create: "Create", edit: "Edit",
  delete: "Delete", username: "Username", password: "Password", register: "Create account", map: "Map",
  list: "List", details: "Details", continueReading: "Continue reading", startNote: "Start note",
  appearance: "Appearance", nose: "Nose", palate: "Palate", reflection: "Reflection",
} as const;

export type TranslationKey = keyof typeof en;

const de: Record<TranslationKey, string> = {
  home:"Start",atlas:"Atlas",tastings:"Verkostungen",cellar:"Keller",profile:"Profil",learn:"Lernen",aromas:"Aromen",admin:"Verwaltung",search:"Die Welt des Weins durchsuchen",explore:"Atlas erkunden",viewRegion:"Region öffnen",addCellar:"Zum Keller hinzufügen",join:"Verkostung beitreten",save:"Speichern",cancel:"Abbrechen",signIn:"Anmelden",signOut:"Abmelden",language:"Sprache",settings:"Einstellungen",openMenu:"Menü öffnen",close:"Schließen",back:"Zurück",all:"Alle",regions:"Regionen",grapes:"Rebsorten",producers:"Erzeuger",wines:"Weine",notes:"Notizen",rating:"Deine Bewertung",owned:"Im Keller",wishlist:"Wunschliste",tasted:"Verkostet",finished:"Ausgetrunken",quantity:"Anzahl",location:"Lagerort",create:"Erstellen",edit:"Bearbeiten",delete:"Löschen",username:"Benutzername",password:"Passwort",register:"Konto erstellen",map:"Karte",list:"Liste",details:"Details",continueReading:"Weiterlesen",startNote:"Notiz beginnen",appearance:"Aussehen",nose:"Nase",palate:"Gaumen",reflection:"Eindruck",
};
const fr: Record<TranslationKey, string> = {
  home:"Accueil",atlas:"Atlas",tastings:"Dégustations",cellar:"Cave",profile:"Profil",learn:"Apprendre",aromas:"Arômes",admin:"Gestion",search:"Explorer le monde du vin",explore:"Explorer l’atlas",viewRegion:"Ouvrir la région",addCellar:"Ajouter à la cave",join:"Rejoindre la dégustation",save:"Enregistrer",cancel:"Annuler",signIn:"Se connecter",signOut:"Se déconnecter",language:"Langue",settings:"Réglages",openMenu:"Ouvrir le menu",close:"Fermer",back:"Retour",all:"Tous",regions:"Régions",grapes:"Cépages",producers:"Producteurs",wines:"Vins",notes:"Notes",rating:"Votre note",owned:"En cave",wishlist:"Envies",tasted:"Dégusté",finished:"Terminé",quantity:"Quantité",location:"Emplacement",create:"Créer",edit:"Modifier",delete:"Supprimer",username:"Identifiant",password:"Mot de passe",register:"Créer un compte",map:"Carte",list:"Liste",details:"Détails",continueReading:"Continuer",startNote:"Commencer une note",appearance:"Robe",nose:"Nez",palate:"Bouche",reflection:"Impression",
};
const es: Record<TranslationKey, string> = {
  home:"Inicio",atlas:"Atlas",tastings:"Catas",cellar:"Bodega",profile:"Perfil",learn:"Aprender",aromas:"Aromas",admin:"Gestión",search:"Explorar el mundo del vino",explore:"Explorar el atlas",viewRegion:"Abrir región",addCellar:"Añadir a la bodega",join:"Unirse a la cata",save:"Guardar",cancel:"Cancelar",signIn:"Iniciar sesión",signOut:"Cerrar sesión",language:"Idioma",settings:"Ajustes",openMenu:"Abrir menú",close:"Cerrar",back:"Atrás",all:"Todos",regions:"Regiones",grapes:"Uvas",producers:"Productores",wines:"Vinos",notes:"Notas",rating:"Tu valoración",owned:"En bodega",wishlist:"Deseos",tasted:"Catado",finished:"Terminado",quantity:"Cantidad",location:"Ubicación",create:"Crear",edit:"Editar",delete:"Eliminar",username:"Usuario",password:"Contraseña",register:"Crear cuenta",map:"Mapa",list:"Lista",details:"Detalles",continueReading:"Seguir leyendo",startNote:"Empezar nota",appearance:"Aspecto",nose:"Nariz",palate:"Boca",reflection:"Impresión",
};

const dictionaries: Record<Locale, Record<TranslationKey, string>> = { en, de, fr, es };

export const localeRegistry = [
  { id: "en" as const, label: "English" }, { id: "de" as const, label: "Deutsch" },
  { id: "fr" as const, label: "Français" }, { id: "es" as const, label: "Español" },
];

export const pageCopy = {
  en: {
    homeEyebrow:'A living map of wine', homeTitle:'Every bottle begins somewhere.', homeDescription:'Follow place into grape, producer, aroma and the memories you make at the table.', regionCount:'regions across six continents', openTonight:'Open tonight', guidedTable:'New world, old vines · A guided five-wine table', joinTime:'Join at 19:30', beginPlace:'Begin with place', landscapes:'Four landscapes, four voices', seeAll:'See all', aromaExplorer:'Aroma explorer', trainMemory:'Train memory, not certainty.', aromaDescription:'A shared sensory language turns a fleeting impression into a path you can follow.', turnWheel:'Turn the wheel', quietLearn:'A quiet place to learn', noticeMore:'Notice more in every glass.', readGuide:'Read the 5-minute guide', collection:'Your collection', cellarStart:'A cellar starts with one remembered bottle', openCellar:'Open cellar', cellarPrivate:'Save a wine you own, hope to find or want to remember. Your collection stays private in this browser.',
    atlasEyebrow:'World atlas', atlasTitle:'The world, by vine', atlasDescription:'Move across borders and follow the climates, grapes and people that give each region its voice.', atlasSearch:'Find a region or country', placesInView:'places in view', selectedPlace:'Selected place', enterRegion:'Enter region',
    aromaEyebrow:'Sensory atlas', aromaTitle:'Turn memory into language', aromaIntro:'Aromas are associations, not ingredients. Choose a wine style, then move from family to a precise point of reference.', followNote:'Follow this note', caveat:'A useful caveat', caveatBody:'“Mineral” language describes a sensory association. It does not mean that stone has dissolved into the wine.',
    learnEyebrow:'Field notes', learnTitle:'Learn by following questions', learnIntro:'Clear foundations for tasting, serving and understanding how style is made.', readStory:'Read the story', continueLearning:'Continue learning', takeTable:'Take this to the table',
    tastingsEyebrow:'Around the table', tastingsTitle:'Taste together, remember your way', tastingsIntro:'Join a guided flight or host a table. Notes can stay private even when the tasting is shared.', openTasting:'Open tasting', tableTitle:'New world, old vines', tableIntro:'Five wines, five landscapes and one question: what does an old vine carry into the glass?', tonight:'Tonight', host:'Host', seats:'Seats', joinTable:'Join the table', invitation:'Have an invitation?', joinCode:'Join with a table code', codeHelp:'Codes are six letters. Your place and notes stay on this device.', comingUp:'Coming up',
    cellarEyebrow:'Personal cellar', cellarTitle:'A collection of future memories', cellarIntro:'Keep what you own, what you hope to find and what you have already tasted—all private to this browser.', addWine:'Add a wine', bottles:'bottles', wishList:'on your wish list', personalRatings:'personal ratings', firstBottle:'Your first bottle can begin anywhere', emptyCellar:'Add something you own, a bottle you tasted, or a wine you hope to meet.', noFilter:'Nothing in this part of your cellar', chooseFilter:'Choose another filter, or add a wine to this collection.',
    profileEyebrow:'Profile & settings', profileGuestTitle:'Make the atlas yours', profileUserIntro:'Your tasting notes, cellar and settings remain on this device.', profileGuestIntro:'Sign in to name the memories you keep in this browser.', guestExplorer:'Guest explorer', localProfile:'Local profile', signedIn:'Signed in on this browser', atlasReady:'Your atlas is ready when you are.', interfaceTranslated:'Interface language for navigation, tools and workflows.', privacy:'Privacy & local data', privacyBody:'Cellar, ratings, tasting notes and account data stay in this browser.', curatorWorkspace:'Curator workspace', curatorBody:'Manage relationships and review catalogue coverage.', localSecurity:'Private on this device', localSecurityBody:'Passwords are hashed before they are stored in this browser. Cellar entries, notes and account data do not leave this device.',
    localAccount:'Local account', welcomeBack:'Welcome back', createProfile:'Create your profile', accountLocal:'Your account and data stay in this browser.', checking:'Checking…', newAccount:'New here? Create an account', existingAccount:'Already have an account? Sign in', curatorAccess:'Curator access', curatorAccessBody:'Use the administrator credentials shared with you separately.',
  },
  de: {
    homeEyebrow:'Eine lebendige Weinkarte', homeTitle:'Jede Flasche beginnt an einem Ort.', homeDescription:'Folge dem Weg vom Ort zur Rebsorte, zum Weingut, zum Aroma und zu den Erinnerungen am Tisch.', regionCount:'Regionen auf sechs Kontinenten', openTonight:'Heute geöffnet', guidedTable:'Neue Welt, alte Reben · Eine geführte Probe mit fünf Weinen', joinTime:'Um 19:30 teilnehmen', beginPlace:'Beginne mit dem Ort', landscapes:'Vier Landschaften, vier Stimmen', seeAll:'Alle ansehen', aromaExplorer:'Aromen entdecken', trainMemory:'Erinnerung schulen, nicht Gewissheit.', aromaDescription:'Eine gemeinsame Sinnessprache macht aus einem flüchtigen Eindruck einen Weg, dem du folgen kannst.', turnWheel:'Aromenrad drehen', quietLearn:'In Ruhe lernen', noticeMore:'Mehr in jedem Glas entdecken.', readGuide:'5-Minuten-Anleitung lesen', collection:'Deine Sammlung', cellarStart:'Ein Keller beginnt mit einer erinnerten Flasche', openCellar:'Keller öffnen', cellarPrivate:'Speichere einen Wein, den du besitzt, suchst oder behalten möchtest. Deine Sammlung bleibt in diesem Browser privat.',
    atlasEyebrow:'Weltatlas', atlasTitle:'Die Welt der Reben', atlasDescription:'Überquere Grenzen und folge Klima, Rebsorten und Menschen, die jeder Region ihre Stimme geben.', atlasSearch:'Region oder Land suchen', placesInView:'Orte sichtbar', selectedPlace:'Ausgewählter Ort', enterRegion:'Region öffnen',
    aromaEyebrow:'Sensorischer Atlas', aromaTitle:'Erinnerung wird Sprache', aromaIntro:'Aromen sind Assoziationen, keine Zutaten. Wähle einen Weinstil und gehe von der Familie zum genauen Bezugspunkt.', followNote:'Diesem Aroma folgen', caveat:'Ein wichtiger Hinweis', caveatBody:'„Mineralisch“ beschreibt eine Sinnesassoziation. Es bedeutet nicht, dass sich Gestein im Wein aufgelöst hat.',
    learnEyebrow:'Feldnotizen', learnTitle:'Lernen, indem du Fragen folgst', learnIntro:'Klare Grundlagen zu Verkostung, Service und der Entstehung von Weinstilen.', readStory:'Artikel lesen', continueLearning:'Weiterlernen', takeTable:'Mit an den Tisch nehmen',
    tastingsEyebrow:'Rund um den Tisch', tastingsTitle:'Gemeinsam probieren, persönlich erinnern', tastingsIntro:'Nimm an einer geführten Probe teil oder lade selbst ein. Deine Notizen können privat bleiben.', openTasting:'Offene Verkostung', tableTitle:'Neue Welt, alte Reben', tableIntro:'Fünf Weine, fünf Landschaften und eine Frage: Was tragen alte Reben ins Glas?', tonight:'Heute', host:'Gastgeberin', seats:'Plätze', joinTable:'Am Tisch teilnehmen', invitation:'Du hast eine Einladung?', joinCode:'Mit Tischcode teilnehmen', codeHelp:'Codes bestehen aus sechs Buchstaben. Dein Platz und deine Notizen bleiben auf diesem Gerät.', comingUp:'Demnächst',
    cellarEyebrow:'Persönlicher Keller', cellarTitle:'Eine Sammlung zukünftiger Erinnerungen', cellarIntro:'Bewahre, was du besitzt, suchst oder bereits probiert hast – privat in diesem Browser.', addWine:'Wein hinzufügen', bottles:'Flaschen', wishList:'auf der Wunschliste', personalRatings:'persönliche Bewertungen', firstBottle:'Deine erste Flasche kann überall beginnen', emptyCellar:'Füge eine eigene, probierte oder gewünschte Flasche hinzu.', noFilter:'In diesem Kellerbereich ist nichts', chooseFilter:'Wähle einen anderen Filter oder füge einen Wein hinzu.',
    profileEyebrow:'Profil & Einstellungen', profileGuestTitle:'Mach den Atlas zu deinem', profileUserIntro:'Verkostungsnotizen, Keller und Einstellungen bleiben auf diesem Gerät.', profileGuestIntro:'Melde dich an und gib deinen Erinnerungen einen Namen.', guestExplorer:'Gast', localProfile:'Lokales Profil', signedIn:'In diesem Browser angemeldet', atlasReady:'Dein Atlas wartet auf dich.', interfaceTranslated:'Sprache für Navigation, Werkzeuge und Abläufe.', privacy:'Privatsphäre & lokale Daten', privacyBody:'Keller, Bewertungen, Verkostungsnotizen und Kontodaten bleiben in diesem Browser.', curatorWorkspace:'Kuratorenbereich', curatorBody:'Beziehungen verwalten und Katalogabdeckung prüfen.', localSecurity:'Privat auf diesem Gerät', localSecurityBody:'Passwörter werden gehasht, bevor sie in diesem Browser gespeichert werden. Keller, Notizen und Kontodaten verlassen dieses Gerät nicht.',
    localAccount:'Lokales Konto', welcomeBack:'Willkommen zurück', createProfile:'Profil erstellen', accountLocal:'Konto und Daten bleiben in diesem Browser.', checking:'Wird geprüft…', newAccount:'Neu hier? Konto erstellen', existingAccount:'Schon registriert? Anmelden', curatorAccess:'Kuratorenzugang', curatorAccessBody:'Nutze die separat mitgeteilten Administrationsdaten.',
  },
  fr: {
    homeEyebrow:'Une carte vivante du vin', homeTitle:'Chaque bouteille commence quelque part.', homeDescription:'Suivez le lieu vers le cépage, le domaine, l’arôme et les souvenirs créés à table.', regionCount:'régions sur six continents', openTonight:'Ouvert ce soir', guidedTable:'Nouveau Monde, vieilles vignes · Cinq vins guidés', joinTime:'Rejoindre à 19 h 30', beginPlace:'Commencer par le lieu', landscapes:'Quatre paysages, quatre voix', seeAll:'Tout voir', aromaExplorer:'Explorer les arômes', trainMemory:'Entraîner la mémoire, pas la certitude.', aromaDescription:'Un langage sensoriel commun transforme une impression fugace en piste à suivre.', turnWheel:'Tourner la roue', quietLearn:'Apprendre au calme', noticeMore:'Mieux remarquer chaque verre.', readGuide:'Lire le guide de 5 minutes', collection:'Votre collection', cellarStart:'Une cave commence par une bouteille mémorable', openCellar:'Ouvrir la cave', cellarPrivate:'Gardez un vin possédé, recherché ou mémorable. Votre collection reste privée dans ce navigateur.',
    atlasEyebrow:'Atlas mondial', atlasTitle:'Le monde, par la vigne', atlasDescription:'Traversez les frontières et suivez les climats, cépages et personnes qui donnent sa voix à chaque région.', atlasSearch:'Chercher une région ou un pays', placesInView:'lieux visibles', selectedPlace:'Lieu sélectionné', enterRegion:'Ouvrir la région',
    aromaEyebrow:'Atlas sensoriel', aromaTitle:'Transformer la mémoire en langage', aromaIntro:'Les arômes sont des associations, pas des ingrédients. Choisissez un style puis allez de la famille à une référence précise.', followNote:'Suivre cet arôme', caveat:'Une précision utile', caveatBody:'Le vocabulaire « minéral » décrit une association sensorielle ; il ne signifie pas que la pierre s’est dissoute dans le vin.',
    learnEyebrow:'Carnet de terrain', learnTitle:'Apprendre en suivant les questions', learnIntro:'Des bases claires pour déguster, servir et comprendre la création d’un style.', readStory:'Lire l’article', continueLearning:'Continuer à apprendre', takeTable:'À retenir à table',
    tastingsEyebrow:'Autour de la table', tastingsTitle:'Déguster ensemble, se souvenir à sa manière', tastingsIntro:'Rejoignez une dégustation guidée ou recevez votre groupe. Vos notes peuvent rester privées.', openTasting:'Dégustation ouverte', tableTitle:'Nouveau Monde, vieilles vignes', tableIntro:'Cinq vins, cinq paysages et une question : que transmet une vieille vigne au verre ?', tonight:'Ce soir', host:'Hôte', seats:'Places', joinTable:'Rejoindre la table', invitation:'Vous avez une invitation ?', joinCode:'Rejoindre avec un code', codeHelp:'Les codes comportent six lettres. Votre place et vos notes restent sur cet appareil.', comingUp:'À venir',
    cellarEyebrow:'Cave personnelle', cellarTitle:'Une collection de souvenirs à venir', cellarIntro:'Gardez ce que vous possédez, recherchez ou avez déjà goûté, en privé dans ce navigateur.', addWine:'Ajouter un vin', bottles:'bouteilles', wishList:'sur votre liste', personalRatings:'notes personnelles', firstBottle:'Votre première bouteille peut venir de partout', emptyCellar:'Ajoutez un vin possédé, dégusté ou recherché.', noFilter:'Aucun vin dans cette partie de la cave', chooseFilter:'Choisissez un autre filtre ou ajoutez un vin.',
    profileEyebrow:'Profil & réglages', profileGuestTitle:'Faites de l’atlas le vôtre', profileUserIntro:'Vos notes, votre cave et vos réglages restent sur cet appareil.', profileGuestIntro:'Connectez-vous pour nommer les souvenirs conservés ici.', guestExplorer:'Visiteur', localProfile:'Profil local', signedIn:'Connecté dans ce navigateur', atlasReady:'Votre atlas vous attend.', interfaceTranslated:'Langue de la navigation, des outils et des parcours.', privacy:'Confidentialité & données locales', privacyBody:'Cave, notes et données du compte restent dans ce navigateur.', curatorWorkspace:'Espace de curation', curatorBody:'Gérer les relations et vérifier la couverture du catalogue.', localSecurity:'Privé sur cet appareil', localSecurityBody:'Les mots de passe sont hachés avant leur stockage dans ce navigateur. Cave, notes et compte ne quittent pas cet appareil.',
    localAccount:'Compte local', welcomeBack:'Bon retour', createProfile:'Créer votre profil', accountLocal:'Votre compte et vos données restent dans ce navigateur.', checking:'Vérification…', newAccount:'Nouveau ici ? Créer un compte', existingAccount:'Déjà inscrit ? Se connecter', curatorAccess:'Accès de curation', curatorAccessBody:'Utilisez les identifiants administrateur transmis séparément.',
  },
  es: {
    homeEyebrow:'Un mapa vivo del vino', homeTitle:'Cada botella empieza en algún lugar.', homeDescription:'Sigue el lugar hasta la uva, la bodega, el aroma y los recuerdos que nacen en la mesa.', regionCount:'regiones en seis continentes', openTonight:'Abierto esta noche', guidedTable:'Nuevo Mundo, viñas viejas · Cinco vinos guiados', joinTime:'Unirse a las 19:30', beginPlace:'Empieza por el lugar', landscapes:'Cuatro paisajes, cuatro voces', seeAll:'Ver todo', aromaExplorer:'Explorar aromas', trainMemory:'Entrena la memoria, no la certeza.', aromaDescription:'Un lenguaje sensorial común convierte una impresión fugaz en un camino que seguir.', turnWheel:'Girar la rueda', quietLearn:'Aprender con calma', noticeMore:'Descubre más en cada copa.', readGuide:'Leer la guía de 5 minutos', collection:'Tu colección', cellarStart:'Una bodega empieza con una botella recordada', openCellar:'Abrir la bodega', cellarPrivate:'Guarda un vino que tengas, busques o quieras recordar. Tu colección permanece privada en este navegador.',
    atlasEyebrow:'Atlas mundial', atlasTitle:'El mundo, por la vid', atlasDescription:'Cruza fronteras y sigue los climas, uvas y personas que dan voz a cada región.', atlasSearch:'Buscar región o país', placesInView:'lugares visibles', selectedPlace:'Lugar seleccionado', enterRegion:'Abrir región',
    aromaEyebrow:'Atlas sensorial', aromaTitle:'Convierte la memoria en lenguaje', aromaIntro:'Los aromas son asociaciones, no ingredientes. Elige un estilo y avanza de la familia a una referencia precisa.', followNote:'Seguir este aroma', caveat:'Una precisión útil', caveatBody:'El lenguaje «mineral» describe una asociación sensorial; no significa que la piedra se haya disuelto en el vino.',
    learnEyebrow:'Notas de campo', learnTitle:'Aprende siguiendo preguntas', learnIntro:'Bases claras para catar, servir y entender cómo se crea un estilo.', readStory:'Leer el artículo', continueLearning:'Seguir aprendiendo', takeTable:'Llévalo a la mesa',
    tastingsEyebrow:'Alrededor de la mesa', tastingsTitle:'Cata en compañía, recuerda a tu manera', tastingsIntro:'Únete a una cata guiada u organiza tu mesa. Tus notas pueden seguir siendo privadas.', openTasting:'Cata abierta', tableTitle:'Nuevo Mundo, viñas viejas', tableIntro:'Cinco vinos, cinco paisajes y una pregunta: ¿qué lleva una viña vieja a la copa?', tonight:'Esta noche', host:'Anfitrión', seats:'Plazas', joinTable:'Unirse a la mesa', invitation:'¿Tienes una invitación?', joinCode:'Entrar con código', codeHelp:'Los códigos tienen seis letras. Tu plaza y tus notas quedan en este dispositivo.', comingUp:'Próximamente',
    cellarEyebrow:'Bodega personal', cellarTitle:'Una colección de recuerdos futuros', cellarIntro:'Guarda lo que tienes, buscas o ya has probado, de forma privada en este navegador.', addWine:'Añadir vino', bottles:'botellas', wishList:'en tu lista', personalRatings:'valoraciones personales', firstBottle:'Tu primera botella puede empezar en cualquier lugar', emptyCellar:'Añade un vino propio, catado o deseado.', noFilter:'No hay vinos en esta parte de la bodega', chooseFilter:'Elige otro filtro o añade un vino.',
    profileEyebrow:'Perfil y ajustes', profileGuestTitle:'Haz tuyo el atlas', profileUserIntro:'Tus notas, bodega y ajustes permanecen en este dispositivo.', profileGuestIntro:'Inicia sesión para dar nombre a los recuerdos guardados aquí.', guestExplorer:'Visitante', localProfile:'Perfil local', signedIn:'Sesión iniciada en este navegador', atlasReady:'Tu atlas está listo.', interfaceTranslated:'Idioma de navegación, herramientas y recorridos.', privacy:'Privacidad y datos locales', privacyBody:'Bodega, notas y datos de cuenta permanecen en este navegador.', curatorWorkspace:'Espacio de curación', curatorBody:'Gestiona relaciones y revisa la cobertura del catálogo.', localSecurity:'Privado en este dispositivo', localSecurityBody:'Las contraseñas se cifran antes de almacenarse en este navegador. Bodega, notas y cuenta no salen de este dispositivo.',
    localAccount:'Cuenta local', welcomeBack:'Bienvenido de nuevo', createProfile:'Crea tu perfil', accountLocal:'Tu cuenta y tus datos permanecen en este navegador.', checking:'Comprobando…', newAccount:'¿Eres nuevo? Crear una cuenta', existingAccount:'¿Ya tienes cuenta? Inicia sesión', curatorAccess:'Acceso de curación', curatorAccessBody:'Usa las credenciales de administración compartidas por separado.',
  },
} as const;

type LocaleValue = { locale: Locale; setLocale: (locale: Locale) => void; t: (key: TranslationKey) => string };
const LocaleContext = createContext<LocaleValue | null>(null);

export function LocaleProvider({ children }: { children: ReactNode }) {
  const [locale, setLocaleState] = useState<Locale>(() => (localStorage.getItem("vine-atlas.locale") as Locale) || "en");
  const value = useMemo<LocaleValue>(() => ({
    locale,
    setLocale: (next) => { localStorage.setItem("vine-atlas.locale", next); setLocaleState(next); },
    t: (key) => dictionaries[locale][key] || en[key],
  }), [locale]);
  return <LocaleContext.Provider value={value}>{children}</LocaleContext.Provider>;
}

export function useLocale() {
  const value = useContext(LocaleContext);
  if (!value) throw new Error("LocaleProvider missing");
  return value;
}

export function usePageCopy() {
  const { locale } = useLocale();
  return pageCopy[locale];
}
