import { CircleMarker, MapContainer, TileLayer } from 'react-leaflet'
import { ArrowRight, Compass, Droplets, FlaskConical, Grape as GrapeIcon, Layers3, Mountain, Route, SunMedium, ThermometerSun, Wine as WineIcon } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { Article, Grape, Producer, Region, Wine } from './types'
import type { Locale } from './i18n'
import { grapes, producers, regions } from './data/catalog'
import { countryLabel, grapeContent, producerContent, regionContent, wineContent } from './localizedContent'
import soilAtlas from './assets/vineyard-soil-atlas.jpg'
import bottleForms from './assets/wine-bottle-forms.jpg'
import darkGrapePlate from './assets/ampelography-dark-grape.jpg'
import lightGrapePlate from './assets/ampelography-light-grape.jpg'

const depthCopy={
  en:{mapEyebrow:'Geographic orientation',mapTitle:'Locate the region before reading its style',mapBody:'The marker uses the atlas coordinate for this region. Zoom level is contextual; appellation boundaries can be much smaller or more complex than the point shown.',soilEyebrow:'Soil field guide',soilTitle:'Read structure, water and roots—not a list of flavours',soilBody:'Geology affects drainage, heat, rooting and vine stress. It does not season wine like an ingredient; the grower’s response remains part of the chain.',water:'Water behaviour',root:'Rooting clue',heat:'Heat and season',compare:'Compare in the atlas',grapeEyebrow:'Variety laboratory',grapeTitle:'One grape, three moving targets',cool:'In a cooler expression',warm:'In a warmer expression',grower:'The grower watches',maker:'The cellar changes',structure:'Structural compass',producerEyebrow:'Estate decision map',producerTitle:'Follow the choices from parcel to bottle',site:'Site and material',harvest:'Harvest threshold',cellar:'Cellar translation',verify:'Primary source',wineEyebrow:'Bottle and evolution',wineTitle:'Read the wine as a sequence, not a snapshot',open:'At opening',air:'With air',table:'At the table',cellarTime:'Across the drinking window',shape:'Bottle shape is history, not a score',shapeBody:'Bordeaux shoulders, Burgundy slopes, slender Rhine forms and pressure-resistant sparkling bottles grew from handling and production needs. None guarantees quality.',lessonEyebrow:'Masterclass extension',lessonTitle:'Turn the lesson into a repeatable skill',myth:'Common shortcut to avoid',mechanism:'Mechanism to explain',comparison:'Comparison to set up',practice:'Practice at the table',question:'A useful next question',connections:'Continue through connected examples'},
  de:{mapEyebrow:'Geografische Orientierung',mapTitle:'Erst die Region verorten, dann ihren Stil lesen',mapBody:'Der Marker nutzt die Atlas-Koordinate dieser Region. Der Zoom dient der Orientierung; Appellationsgrenzen können deutlich kleiner oder komplexer sein als der gezeigte Punkt.',soilEyebrow:'Boden-Feldführer',soilTitle:'Struktur, Wasser und Wurzeln lesen – keine Aromaliste',soilBody:'Geologie beeinflusst Drainage, Wärme, Durchwurzelung und Stress der Rebe. Sie würzt Wein nicht wie eine Zutat; die Reaktion des Winzers bleibt Teil der Kette.',water:'Wasserverhalten',root:'Hinweis zur Durchwurzelung',heat:'Wärme und Saison',compare:'Im Atlas vergleichen',grapeEyebrow:'Rebsortenlabor',grapeTitle:'Eine Rebsorte, drei bewegliche Ziele',cool:'In einer kühleren Ausprägung',warm:'In einer wärmeren Ausprägung',grower:'Darauf achtet der Winzer',maker:'Das verändert der Keller',structure:'Struktureller Kompass',producerEyebrow:'Entscheidungskarte des Weinguts',producerTitle:'Die Entscheidungen von der Parzelle bis zur Flasche verfolgen',site:'Standort und Material',harvest:'Schwelle für die Lese',cellar:'Übersetzung im Keller',verify:'Primärquelle',wineEyebrow:'Flasche und Entwicklung',wineTitle:'Den Wein als Verlauf lesen, nicht als Momentaufnahme',open:'Beim Öffnen',air:'Mit Luft',table:'Am Tisch',cellarTime:'Im Trinkfenster',shape:'Flaschenform ist Geschichte, keine Bewertung',shapeBody:'Bordeaux-Schultern, Burgunderform, schlanke Rheinflaschen und druckfeste Schaumweinflaschen entstanden aus Handhabung und Produktion. Keine Form garantiert Qualität.',lessonEyebrow:'Masterclass-Erweiterung',lessonTitle:'Aus Wissen eine wiederholbare Fähigkeit machen',myth:'Verkürzung, die du vermeiden solltest',mechanism:'Mechanismus, den du erklären kannst',comparison:'Vergleich, den du aufbauen kannst',practice:'Übung am Tisch',question:'Eine sinnvolle nächste Frage',connections:'Mit verbundenen Beispielen fortfahren'},
  fr:{mapEyebrow:'Orientation géographique',mapTitle:'Situer la région avant de lire son style',mapBody:'Le repère utilise la coordonnée de l’atlas. Le niveau de zoom donne un contexte ; les limites d’une appellation peuvent être bien plus petites ou complexes que ce point.',soilEyebrow:'Guide de terrain des sols',soilTitle:'Lire structure, eau et racines — pas une liste de saveurs',soilBody:'La géologie agit sur drainage, chaleur, enracinement et stress. Elle n’assaisonne pas le vin ; la réponse du vigneron reste un maillon essentiel.',water:'Comportement de l’eau',root:'Indice d’enracinement',heat:'Chaleur et saison',compare:'Comparer dans l’atlas',grapeEyebrow:'Laboratoire du cépage',grapeTitle:'Un cépage, trois cibles mobiles',cool:'Dans une expression plus fraîche',warm:'Dans une expression plus chaude',grower:'Ce que surveille le vigneron',maker:'Ce que change la cave',structure:'Boussole structurelle',producerEyebrow:'Carte des décisions du domaine',producerTitle:'Suivre les choix de la parcelle à la bouteille',site:'Site et matière',harvest:'Seuil de vendange',cellar:'Traduction en cave',verify:'Source primaire',wineEyebrow:'Bouteille et évolution',wineTitle:'Lire le vin comme une séquence, non un instant',open:'À l’ouverture',air:'Avec l’air',table:'À table',cellarTime:'Dans sa fenêtre',shape:'La forme raconte une histoire, pas une note',shapeBody:'Épaules bordelaises, pente bourguignonne, flûte rhénane et verre résistant des effervescents viennent de besoins pratiques. Aucune forme ne garantit la qualité.',lessonEyebrow:'Extension masterclass',lessonTitle:'Transformer la leçon en savoir-faire répétable',myth:'Raccourci à éviter',mechanism:'Mécanisme à expliquer',comparison:'Comparaison à préparer',practice:'Exercice à table',question:'Prochaine question utile',connections:'Continuer avec des exemples reliés'},
  es:{mapEyebrow:'Orientación geográfica',mapTitle:'Sitúa la región antes de interpretar su estilo',mapBody:'El marcador usa la coordenada del atlas. El zoom aporta contexto; los límites de una denominación pueden ser mucho menores o más complejos que el punto.',soilEyebrow:'Guía de campo de suelos',soilTitle:'Lee estructura, agua y raíces, no una lista de sabores',soilBody:'La geología influye en drenaje, calor, raíces y estrés. No sazona el vino como un ingrediente; la respuesta del viticultor sigue siendo parte de la cadena.',water:'Comportamiento del agua',root:'Pista de enraizamiento',heat:'Calor y temporada',compare:'Comparar en el atlas',grapeEyebrow:'Laboratorio de variedades',grapeTitle:'Una variedad, tres objetivos móviles',cool:'En una expresión más fresca',warm:'En una expresión más cálida',grower:'Lo que vigila el viticultor',maker:'Lo que cambia la bodega',structure:'Brújula estructural',producerEyebrow:'Mapa de decisiones de la bodega',producerTitle:'Sigue las decisiones de la parcela a la botella',site:'Lugar y material',harvest:'Umbral de vendimia',cellar:'Traducción en bodega',verify:'Fuente primaria',wineEyebrow:'Botella y evolución',wineTitle:'Lee el vino como secuencia, no como instante',open:'Al abrir',air:'Con aire',table:'En la mesa',cellarTime:'En su ventana',shape:'La forma es historia, no puntuación',shapeBody:'Hombros bordeleses, pendiente borgoñona, botella renana y vidrio resistente para espumosos nacieron de necesidades prácticas. Ninguna forma garantiza calidad.',lessonEyebrow:'Extensión masterclass',lessonTitle:'Convierte la lección en una habilidad repetible',myth:'Atajo que conviene evitar',mechanism:'Mecanismo que debes explicar',comparison:'Comparación que puedes preparar',practice:'Práctica en la mesa',question:'Una siguiente pregunta útil',connections:'Continuar con ejemplos conectados'},
} as const

const soilLibrary={
  limestone:{pattern:/limestone|chalk|calcareous|marl|kalk|craie|calcaire/i,title:{en:'Limestone & chalk',de:'Kalkstein & Kreide',fr:'Calcaire & craie',es:'Caliza & tiza'},water:{en:'Fractures and fine pores can combine drainage with useful reserves.',de:'Klüfte und feine Poren können Drainage mit nutzbaren Reserven verbinden.',fr:'Fissures et pores fins peuvent unir drainage et réserve utile.',es:'Fisuras y poros finos pueden unir drenaje y reserva útil.'},root:{en:'Roots exploit cracks, softer marl bands and biological channels.',de:'Wurzeln nutzen Risse, weichere Mergelbänder und biologische Kanäle.',fr:'Les racines suivent fissures, marnes tendres et canaux biologiques.',es:'Las raíces siguen fisuras, margas blandas y canales biológicos.'}},
  slate:{pattern:/slate|schist|schiefer|ardoise|pizarra/i,title:{en:'Slate & schist',de:'Schiefer',fr:'Schiste & ardoise',es:'Pizarra & esquisto'},water:{en:'Thin fractured layers shed water quickly but can hold it deep in fissures.',de:'Dünne Bruchschichten leiten Wasser rasch ab, halten es aber tief in Klüften.',fr:'Les feuillets drainent vite mais gardent parfois l’eau en profondeur.',es:'Las láminas drenan rápido, aunque guardan agua en fisuras profundas.'},root:{en:'Roots search vertically and laterally through fractured planes.',de:'Wurzeln suchen vertikal und seitlich entlang der Bruchflächen.',fr:'Les racines explorent verticalement et latéralement les fractures.',es:'Las raíces exploran en vertical y lateral las fracturas.'}},
  clay:{pattern:/clay|loam|loess|ton|argile|arcilla/i,title:{en:'Clay & loam',de:'Ton & Lehm',fr:'Argile & limon',es:'Arcilla & limo'},water:{en:'Fine particles hold water and nutrients; compaction and timing matter.',de:'Feine Partikel halten Wasser und Nährstoffe; Verdichtung und Timing zählen.',fr:'Les particules fines retiennent eau et nutriments ; le tassement compte.',es:'Las partículas finas guardan agua y nutrientes; importa la compactación.'},root:{en:'Roots favour cracks, aggregate edges and biologically active zones.',de:'Wurzeln bevorzugen Risse, Aggregatränder und biologisch aktive Zonen.',fr:'Les racines préfèrent fissures, agrégats et zones biologiquement actives.',es:'Las raíces prefieren grietas, agregados y zonas biológicamente activas.'}},
  granite:{pattern:/granite|granitic|granit/i,title:{en:'Granite',de:'Granit',fr:'Granit',es:'Granito'},water:{en:'Weathered granite often drains freely; depth determines reserve.',de:'Verwitterter Granit drainiert oft frei; die Tiefe bestimmt die Reserve.',fr:'Le granit altéré draine librement ; la profondeur règle la réserve.',es:'El granito meteorizado drena bien; la profundidad marca la reserva.'},root:{en:'Roots use decomposed pockets and joints between harder blocks.',de:'Wurzeln nutzen Zersatzzonen und Fugen zwischen härteren Blöcken.',fr:'Les racines utilisent arènes et joints entre blocs plus durs.',es:'Las raíces aprovechan arenas y juntas entre bloques duros.'}},
  volcanic:{pattern:/volcanic|basalt|lava|vulkan|volcanique|volcán/i,title:{en:'Volcanic material',de:'Vulkangestein',fr:'Roche volcanique',es:'Roca volcánica'},water:{en:'Porosity varies strongly between ash, tuff, lava and basalt.',de:'Die Porosität variiert stark zwischen Asche, Tuff, Lava und Basalt.',fr:'La porosité varie fortement entre cendres, tuf, lave et basalte.',es:'La porosidad cambia mucho entre ceniza, toba, lava y basalto.'},root:{en:'Roots exploit vesicles, ash layers and boundaries between flows.',de:'Wurzeln nutzen Blasenräume, Aschelagen und Grenzen zwischen Strömen.',fr:'Les racines suivent vacuoles, cendres et limites entre coulées.',es:'Las raíces siguen vesículas, cenizas y límites entre coladas.'}},
  gravel:{pattern:/gravel|sand|alluvial|kies|sand|gravier|sable|grava|arena/i,title:{en:'Gravel, sand & alluvium',de:'Kies, Sand & Schwemmland',fr:'Graviers, sable & alluvions',es:'Grava, arena y aluvión'},water:{en:'Coarse material drains rapidly; fine layers and water table set reserves.',de:'Grobes Material drainiert rasch; Feinlagen und Grundwasser setzen Reserven.',fr:'Les éléments grossiers drainent vite ; fines et nappe fixent la réserve.',es:'El material grueso drena rápido; finos y nivel freático fijan la reserva.'},root:{en:'Roots travel through interstices and follow buried finer horizons.',de:'Wurzeln wachsen durch Zwischenräume und folgen feineren Horizonten.',fr:'Les racines traversent les interstices et suivent les horizons fins.',es:'Las raíces pasan por intersticios y siguen horizontes más finos.'}},
} as const

function mapZoom(country:string){return ['United States','Canada','Argentina','Chile','Australia','China','South Africa','India'].includes(country)?3:['France','Italy','Spain','Germany','Portugal','New Zealand','Japan'].includes(country)?5:4}

export function RegionFieldGuide({region,locale}:{region:Region;locale:Locale}){
  const c=depthCopy[locale],content=regionContent(region,locale),matches=Object.values(soilLibrary).filter(entry=>entry.pattern.test(`${region.soil} ${content.soil}`)).slice(0,3)
  const guides=matches.length?matches:[soilLibrary.gravel]
  return <section className="region-field-guide">
    <div className="locator-card"><div className="depth-heading"><span className="eyebrow">{c.mapEyebrow}</span><h2>{c.mapTitle}</h2><p>{c.mapBody}</p></div><div className="mini-region-map"><MapContainer key={region.id} center={[region.lat,region.lng]} zoom={mapZoom(region.country)} scrollWheelZoom={false} dragging={false} doubleClickZoom={false} zoomControl={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png"/><CircleMarker center={[region.lat,region.lng]} radius={9} pathOptions={{color:'#f7efe3',fillColor:'#7d2638',fillOpacity:1,weight:3}}/></MapContainer><span><Compass/>{region.name} · {countryLabel(region.country,locale)}</span></div></div>
    <div className="soil-atlas-card"><img src={soilAtlas} alt=""/><div className="depth-heading"><span className="eyebrow">{c.soilEyebrow}</span><h2>{c.soilTitle}</h2><p>{c.soilBody}</p></div><div className="soil-guide-grid">{guides.map(guide=><article key={guide.title.en}><Layers3/><h3>{guide.title[locale]}</h3><dl><div><dt>{c.water}</dt><dd>{guide.water[locale]}</dd></div><div><dt>{c.root}</dt><dd>{guide.root[locale]}</dd></div></dl></article>)}</div></div>
  </section>
}

export function GrapeDeepDive({grape,locale}:{grape:Grape;locale:Locale}){
  const c=depthCopy[locale],content=grapeContent(grape,locale)
  const structureLabels={en:['Acidity','Tannin','Body'],de:['Säure','Tannin','Körper'],fr:['Acidité','Tanins','Corps'],es:['Acidez','Tanino','Cuerpo']}[locale]
  const climate={en:{cool:`Longer hang time can preserve ${grape.acidity>=4?'a firm acid line':'delicacy'} while delaying sugar; site exposure and crop load decide whether flavour catches up.`,warm:`Faster sugar accumulation can broaden fruit and body. Shade, water balance and picking date protect definition.`,watch:`Canopy light, berry health, yield, seed and skin maturity, and the gap between sugar and flavour.`,make:content.winemaking},de:{cool:`Längere Reife kann ${grape.acidity>=4?'eine feste Säurelinie':'Feinheit'} erhalten und Zucker bremsen; Exposition und Ertrag entscheiden, ob das Aroma nachzieht.`,warm:'Schnellere Zuckerreife kann Frucht und Körper verbreitern. Schatten, Wasserbalance und Lesezeit schützen die Kontur.',watch:'Licht in der Laubwand, Beerengesundheit, Ertrag, Kern- und Schalenreife sowie der Abstand zwischen Zucker und Aroma.',make:content.winemaking},fr:{cool:`Une maturation plus longue peut garder ${grape.acidity>=4?'une acidité ferme':'la finesse'} et ralentir le sucre ; exposition et charge décident si l’arôme suit.`,warm:'Le sucre plus rapide élargit fruit et corps. Ombre, eau et date de récolte gardent la précision.',watch:'Lumière du feuillage, santé des baies, rendement, maturité des pépins et des peaux, écart entre sucre et arôme.',make:content.winemaking},es:{cool:`Una maduración más larga puede conservar ${grape.acidity>=4?'una acidez firme':'delicadeza'} y frenar el azúcar; exposición y carga deciden si alcanza el aroma.`,warm:'La acumulación rápida de azúcar amplía fruta y cuerpo. Sombra, agua y vendimia conservan definición.',watch:'Luz en la vegetación, sanidad, rendimiento, madurez de semillas y pieles, distancia entre azúcar y aroma.',make:content.winemaking}}[locale]
  return <section className="grape-deep-dive"><div className="depth-heading"><span className="eyebrow">{c.grapeEyebrow}</span><h2>{c.grapeTitle}</h2></div><div className="climate-comparison"><article><ThermometerSun/><span>{c.cool}</span><p>{climate.cool}</p></article><article><SunMedium/><span>{c.warm}</span><p>{climate.warm}</p></article><article><GrapeIcon/><span>{c.grower}</span><p>{climate.watch}</p></article><article><FlaskConical/><span>{c.maker}</span><p>{climate.make}</p></article></div><div className="structure-compass"><span>{c.structure}</span>{([[structureLabels[0],grape.acidity],[structureLabels[1],grape.tannin],[structureLabels[2],grape.body]] as const).map(([label,value])=><div key={label}><small>{label}</small><i><b style={{width:`${value*20}%`}}/></i><strong>{value}/5</strong></div>)}</div></section>
}

const ampelographyProfiles:Record<string,{leaf:string;cluster:string;berry:string;growth:string;risk:string}>={
  riesling:{leaf:'small-to-medium, round and often five-lobed, with a distinctly coarse, blistered surface and overlapping petiolar sinus','cluster':'small, compact and usually cylindrical, sometimes with a short wing','berry':'small, round, yellow-green and dotted at full maturity; the skin remains relatively firm','growth':'upright growth, comparatively hard wood and early budbreak followed by late ripening','risk':'early buds are frost-exposed; compact bunches can invite botrytis, although healthy noble rot is valuable for sweet styles'},
  chardonnay:{leaf:'medium, broadly orbicular and only lightly lobed; the open petiolar sinus is often bordered by nearly naked veins','cluster':'small-to-medium, cylindrical and moderately compact, frequently shouldered','berry':'small, round and thin-skinned, changing from green to golden amber in exposed sites','growth':'early budbreak and early ripening with vigorous shoot growth when water and nitrogen are abundant','risk':'spring frost, coulure or millerandage around flowering, powdery mildew and botrytis in tight bunches'},
  'cabernet-sauvignon':{leaf:'medium, deeply five-lobed, with characteristic overlapping lobes that make the blade look almost perforated','cluster':'small-to-medium, conical, loose-to-moderately compact and often winged','berry':'small, spherical, blue-black and thick-skinned, with a high skin-to-juice ratio','growth':'upright and vigorous, late budding and late ripening; lignification and exposure matter in cool seasons','risk':'late maturity can leave pyrazine-led green character; drought, trunk disease and poor fruit set require site-specific management'},
  'pinot-noir':{leaf:'small-to-medium, thick and round with three to five shallow lobes and a slightly bullate surface','cluster':'small, compact and pine-cone shaped—the source of the Pinot name','berry':'small, spherical, thin-skinned and blue-black, packed closely within the bunch','growth':'early budding and early ripening, with compact architecture and modest natural fertility','risk':'spring frost, millerandage, botrytis and bunch rot; thin skins make handling and extraction especially consequential'},
  'sauvignon-blanc':{leaf:'small-to-medium, round and markedly lobed, with a blistered upper surface and wavy margins','cluster':'small-to-medium, cylindrical, compact and often winged','berry':'small, green-yellow and thick enough to retain aromatic precursors, becoming spotted with sun exposure','growth':'vigorous and often sprawling, early-to-mid budding and mid-season ripening','risk':'vigour can shade fruit and preserve overt green notes; compact bunches are vulnerable to botrytis and powdery mildew'},
  syrah:{leaf:'medium, three-to-five lobed with a distinctly open petiolar sinus and fine down on the underside','cluster':'small-to-medium, elongated, cylindrical-conical and moderately compact','berry':'small, oval, blue-black and relatively thick-skinned','growth':'long, fragile shoot tips and semi-erect growth; mid budding and mid-to-late ripening','risk':'wind damage, drought stress, poor flowering in cold conditions and Syrah decline; exposed berries can shrivel in extreme heat'},
  nebbiolo:{leaf:'medium-to-large, pentagonal and deeply lobed, with a strongly blistered surface and downy underside','cluster':'medium-to-large, elongated, winged and moderately compact','berry':'medium, round-to-ellipsoid, blue-violet with abundant bloom and comparatively thin skin','growth':'vigorous, early budding and very late ripening; the long season makes aspect decisive','risk':'spring frost, rain or fog near harvest, uneven set and delayed lignification on poorly exposed sites'},
  sangiovese:{leaf:'medium, three-to-five lobed and longer than wide, with pronounced upper lateral sinuses','cluster':'medium-to-large, cylindrical-conical, winged and moderately compact','berry':'medium, oval, blue-violet with a moderately thick skin','growth':'vigorous and productive with mid budding and late ripening; clonal diversity changes bunch architecture','risk':'uneven ripening, botrytis in compact material, drought stress and dilution when crop load exceeds site capacity'},
  'grenache-garnacha':{leaf:'medium, wedge-shaped and five-lobed, with a smooth surface and noticeably hairless underside','cluster':'medium-to-large, conical, winged and moderately compact','berry':'medium, round, blue-black and relatively thin-skinned despite its warm-climate adaptation','growth':'upright, very vigorous and wind-resistant, with early budding and late ripening','risk':'coulure, downy mildew, trunk disease and rapid sugar accumulation in hot conditions; old bush vines limit vigour naturally'},
  tempranillo:{leaf:'large, pentagonal and five-lobed, with a blistered surface and a woolly underside','cluster':'medium-to-large, cylindrical-conical, winged and compact','berry':'medium, round, blue-black and moderately thick-skinned','growth':'upright-to-semi-erect, early ripening as its name suggests, with relatively short seasonal cycle','risk':'drought can stop ripening, while compact bunches raise botrytis risk; fertility and yields need active control'},
  'chenin-blanc':{leaf:'medium, round and three-to-five lobed, with a blistered surface and reddish veins near the petiole','cluster':'medium, conical, winged and compact','berry':'small-to-medium, oval, yellow-green and thin-skinned, often taking amber freckles','growth':'early budding and late ripening, naturally vigorous and capable of high acidity across a long season','risk':'spring frost, uneven maturity within the bunch, sunburn and botrytis—the last can be either fault or asset depending on style'},
  malbec:{leaf:'medium, round to pentagonal and usually three-lobed, with a broad open petiolar sinus','cluster':'medium, loose-to-moderately compact and broadly conical','berry':'medium, round, blue-black and comparatively thin-skinned','growth':'upright but brittle, early budding and mid-season ripening with sensitivity around flowering','risk':'spring frost, coulure, downy mildew and trunk disease; altitude and sunlight can thicken skins and deepen colour'},
}

function ampelographyText(grape:Grape,locale:Locale){
  const exact=ampelographyProfiles[grape.id]
  const fallback={
    leaf:`A mature ${grape.name} leaf should be read through blade shape, lobe depth, petiolar sinus, teeth, surface blistering and the density of hairs beneath. Compare several healthy mid-shoot leaves; one leaf is never enough for identification.`,
    cluster:`Record bunch size, winging and compactness at full maturity. ${grape.ripening} changes the field date on which that comparison is meaningful.`,
    berry:`Observe berry size and shape, skin colour, bloom, skin toughness, seed maturity and how tightly berries touch. ${grape.color==='red'?'Dark skin alone does not distinguish cultivars.':'Sun exposure can shift green fruit toward gold or amber without changing the cultivar.'}`,
    growth:`${grape.viticulture} Shoot posture, internode length, tendrils, vigour and timing of budbreak add evidence beyond the fruit.`,
    risk:`Use the plate as an observation protocol, not a positive cultivar diagnosis. Virus status, clone, rootstock, water and canopy can alter appearance; confirm uncertain material with certified records or DNA.`
  }
  const source=exact??fallback
  if(locale==='en') return source
  const timing=grape.ripening.toLowerCase()
  return {
    de:{leaf:`Ein reifes Blatt von ${grape.name} wird über Form, Lappung, Stielbucht, Zähne, Blasigkeit und Behaarung der Unterseite gelesen. Mehrere gesunde Blätter aus der mittleren Triebzone vergleichen – ein Einzelblatt genügt nie.`,cluster:`Größe, Schulterung und Kompaktheit der Traube bei voller Reife erfassen. Der Reifezeitpunkt „${timing}“ bestimmt, wann der Vergleich im Feld sinnvoll ist.`,berry:`Beerengröße und -form, Schalenfarbe, Bereifung, Festigkeit, Kernreife und den Kontakt zwischen den Beeren prüfen. ${grape.color==='red'?'Eine dunkle Schale allein identifiziert keine Rebsorte.':'Sonne kann grüne Beeren goldgelb färben, ohne die Sortenidentität zu ändern.'}`,growth:`Triebhaltung, Internodien, Ranken, Wuchskraft und Austriebszeit liefern neben der Frucht weitere Indizien. Im Weinberg zählen außerdem Laubwand, Ertrag und gleichmäßige Reife.`,risk:'Die Tafel ist ein Beobachtungsprotokoll, keine sichere Sortendiagnose. Klon, Unterlage, Wasser, Virusstatus und Laubwand verändern das Bild; unklare Reben über Pflanzunterlagen oder DNA bestätigen.'},
    fr:{leaf:`Une feuille adulte de ${grape.name} se lit par la forme, les lobes, le sinus pétiolaire, les dents, la gaufrure et le duvet inférieur. Comparez plusieurs feuilles saines : une seule ne suffit jamais.`,cluster:`Notez taille, ailes et compacité à pleine maturité. Le rythme « ${timing} » détermine le bon moment d’observation.`,berry:`Observez taille, forme, couleur, pruine, résistance de la peau, pépins et contact entre baies. ${grape.color==='red'?'La pellicule foncée seule n’identifie pas un cépage.':'Le soleil peut faire passer le vert à l’or sans changer l’identité du cépage.'}`,growth:'Port des rameaux, entre-nœuds, vrilles, vigueur et date de débourrement ajoutent des indices au fruit. Feuillage, charge et homogénéité de maturité complètent la lecture.',risk:'Cette planche est un protocole d’observation, non un diagnostic. Clone, porte-greffe, eau, viroses et feuillage changent l’aspect ; confirmez par les registres ou l’ADN.'},
    es:{leaf:`Una hoja adulta de ${grape.name} se lee por forma, lóbulos, seno peciolar, dientes, abullonado y vello inferior. Compara varias hojas sanas: una sola nunca basta.`,cluster:`Registra tamaño, alas y compacidad en madurez plena. El ritmo «${timing}» determina el momento útil de comparación.`,berry:`Observa tamaño, forma, color, pruina, dureza de piel, semillas y contacto entre bayas. ${grape.color==='red'?'La piel oscura por sí sola no identifica la variedad.':'El sol puede llevar el verde al dorado sin cambiar la identidad varietal.'}`,growth:'Porte, entrenudos, zarcillos, vigor y fecha de brotación aportan evidencia además del fruto. Vegetación, carga y uniformidad de madurez completan la lectura.',risk:'La lámina es un protocolo de observación, no un diagnóstico. Clon, portainjerto, agua, virus y vegetación cambian el aspecto; confirma con registros o ADN.'}
  }[locale]
}

export function GrapeAmpelography({grape,locale}:{grape:Grape;locale:Locale}){
  const copy={en:{eyebrow:'Ampelography field plate',title:'Read the vine before the label',leaf:'Mature leaf',cluster:'Cluster architecture',berry:'Berry & skin',growth:'Growth habit',risk:'Field risks',note:'The illustration is an original generic anatomical guide. Text describes the cultivar where a dependable field profile is available; visual identification should always use several organs and be confirmed.'},de:{eyebrow:'Ampelografische Feldtafel',title:'Die Rebe vor dem Etikett lesen',leaf:'Ausgewachsenes Blatt',cluster:'Traubenarchitektur',berry:'Beere & Schale',growth:'Wuchsverhalten',risk:'Risiken im Feld',note:'Die Illustration ist eine eigenständige anatomische Orientierung. Der Text beschreibt die Sorte, wo ein belastbares Feldprofil vorliegt; visuelle Bestimmung nutzt stets mehrere Organe und wird bestätigt.'},fr:{eyebrow:'Planche ampélographique',title:'Lire la vigne avant l’étiquette',leaf:'Feuille adulte',cluster:'Architecture de grappe',berry:'Baie et pellicule',growth:'Port végétatif',risk:'Risques au vignoble',note:'L’illustration est un guide anatomique générique original. Le texte décrit le cépage quand un profil fiable existe ; toute identification visuelle croise plusieurs organes et doit être confirmée.'},es:{eyebrow:'Lámina ampelográfica',title:'Lee la vid antes de la etiqueta',leaf:'Hoja adulta',cluster:'Arquitectura del racimo',berry:'Baya y piel',growth:'Porte vegetativo',risk:'Riesgos de campo',note:'La ilustración es una guía anatómica genérica y original. El texto describe la variedad cuando existe un perfil fiable; la identificación visual cruza varios órganos y debe confirmarse.'}}[locale]
  const profile=ampelographyText(grape,locale)
  const items=[['leaf',copy.leaf],['cluster',copy.cluster],['berry',copy.berry],['growth',copy.growth],['risk',copy.risk]] as const
  return <section className="ampelography-plate"><figure><img src={grape.color==='red'?darkGrapePlate:lightGrapePlate} alt=""/><figcaption>{copy.note}</figcaption></figure><div><div className="depth-heading"><span className="eyebrow">{copy.eyebrow}</span><h2>{copy.title}</h2></div><dl>{items.map(([key,label])=><div key={key}><dt>{label}</dt><dd>{profile[key]}</dd></div>)}</dl></div></section>
}

export function ProducerDecisionMap({producer,region,locale}:{producer:Producer;region:Region;locale:Locale}){
  const c=depthCopy[locale],p=producerContent(producer,region,locale),r=regionContent(region,locale)
  return <section className="producer-decision-map"><div className="depth-heading"><span className="eyebrow">{c.producerEyebrow}</span><h2>{c.producerTitle}</h2></div><ol><li><span>01</span><Mountain/><div><h3>{c.site}</h3><p>{p.vineyard} {r.soil}</p></div></li><li><span>02</span><SunMedium/><div><h3>{c.harvest}</h3><p>{r.growingSeason}</p></div></li><li><span>03</span><FlaskConical/><div><h3>{c.cellar}</h3><p>{p.cellar}</p></div></li></ol><a className="text-link" href={producer.sourceUrl} target="_blank" rel="noreferrer">{c.verify}<ArrowRight/></a></section>
}

export function WineEvolutionLesson({wine,locale}:{wine:Wine;locale:Locale}){
  const c=depthCopy[locale],producer=producers.find(entry=>entry.id===wine.producerId)!,region=regions.find(entry=>entry.id===wine.regionId)!,content=wineContent(wine,producer,region,locale)
  const sequences={en:[['At opening',`Begin at ${content.serving}. Note fruit, reduction or oak before deciding whether the wine needs air.`],['With air',`Watch whether aroma separates, tannin relaxes and acidity becomes clearer. Air reveals structure; it cannot repair imbalance.`],['At the table',content.pairings.join(' · ')],['Across the drinking window',content.drinkWindow]],de:[['Beim Öffnen',`Beginne bei ${content.serving}. Notiere Frucht, Reduktion oder Holz, bevor du über mehr Luft entscheidest.`],['Mit Luft','Beobachte, ob sich Aromen trennen, Tannin entspannt und Säure klarer wird. Luft zeigt Struktur; sie repariert kein Ungleichgewicht.'],['Am Tisch',content.pairings.join(' · ')],['Im Trinkfenster',content.drinkWindow]],fr:[['À l’ouverture',`Commencez à ${content.serving}. Notez fruit, réduction ou bois avant de décider de l’aération.`],['Avec l’air','Observez si les arômes se séparent, les tanins se détendent et l’acidité se précise. L’air révèle ; il ne répare pas.'],['À table',content.pairings.join(' · ')],['Dans sa fenêtre',content.drinkWindow]],es:[['Al abrir',`Empieza a ${content.serving}. Anota fruta, reducción o roble antes de decidir si necesita aire.`],['Con aire','Observa si los aromas se separan, el tanino se relaja y la acidez gana claridad. El aire revela; no corrige.'],['En la mesa',content.pairings.join(' · ')],['En su ventana',content.drinkWindow]]}[locale]
  return <section className="wine-evolution-lesson"><figure><img src={bottleForms} alt=""/><figcaption><strong>{c.shape}</strong><span>{c.shapeBody}</span></figcaption></figure><div><div className="depth-heading"><span className="eyebrow">{c.wineEyebrow}</span><h2>{c.wineTitle}</h2></div><ol>{sequences.map(([title,body],index)=><li key={title}><span>0{index+1}</span><div><h3>{title}</h3><p>{body}</p></div></li>)}</ol></div></section>
}

export function AcademyMasterclass({article,locale}:{article:Article;locale:Locale}){
  const c=depthCopy[locale],region=regions.find(entry=>article.relatedRegionIds.includes(entry.id)),grape=grapes.find(entry=>article.relatedGrapeIds.includes(entry.id))
  const text={en:{myth:'A single rule explains every wine. In practice, vintage, site, material and intention interact.',mechanism:`Explain ${article.title.toLowerCase()} as a chain of choices, then name the sensory evidence each step could leave.`,comparison:`Keep one variable steady: compare two wines from ${region?.name??'one region'} or two expressions of ${grape?.name??'one grape'}.`,practice:'Describe first, interpret second. Write three observations before naming cause or quality.',question:'What observation would prove your first explanation wrong?'},de:{myth:'Eine einzelne Regel erklärt jeden Wein. Tatsächlich wirken Jahrgang, Standort, Material und Absicht zusammen.',mechanism:`Erkläre „${article.title}“ als Kette von Entscheidungen und nenne für jeden Schritt mögliche sensorische Spuren.`,comparison:`Halte eine Variable konstant: Vergleiche zwei Weine aus ${region?.name??'einer Region'} oder zwei Ausprägungen von ${grape?.name??'einer Rebsorte'}.`,practice:'Erst beschreiben, dann deuten. Notiere drei Beobachtungen, bevor du Ursache oder Qualität benennst.',question:'Welche Beobachtung würde deine erste Erklärung widerlegen?'},fr:{myth:'Une règle unique n’explique jamais tous les vins. Millésime, lieu, matière et intention interagissent.',mechanism:`Expliquez « ${article.title} » comme une chaîne de choix et reliez chaque étape à une trace sensorielle possible.`,comparison:`Gardez une variable constante : deux vins de ${region?.name??'la même région'} ou deux expressions de ${grape?.name??'un même cépage'}.`,practice:'Décrire avant d’interpréter. Notez trois observations avant de nommer cause ou qualité.',question:'Quelle observation réfuterait votre première explication ?'},es:{myth:'Una sola regla no explica todos los vinos. Añada, lugar, material e intención interactúan.',mechanism:`Explica «${article.title}» como cadena de decisiones y relaciona cada paso con una huella sensorial.`,comparison:`Mantén una variable: dos vinos de ${region?.name??'la misma región'} o dos expresiones de ${grape?.name??'una variedad'}.`,practice:'Describe antes de interpretar. Anota tres observaciones antes de nombrar causa o calidad.',question:'¿Qué observación demostraría que tu primera explicación es incorrecta?'}}[locale]
  const rows=[['myth',c.myth],['mechanism',c.mechanism],['comparison',c.comparison],['practice',c.practice],['question',c.question]] as const
  return <section className="academy-masterclass"><div className="depth-heading"><span className="eyebrow">{c.lessonEyebrow}</span><h2>{c.lessonTitle}</h2></div><div>{rows.map(([key,label],index)=><article key={key}><span>0{index+1}</span><h3>{label}</h3><p>{text[key]}</p></article>)}</div><aside><Route/><strong>{c.connections}</strong>{region&&<Link to={`/regions/${region.id}`}>{region.name}<ArrowRight/></Link>}{grape&&<Link to={`/grapes/${grape.id}`}>{grape.name}<ArrowRight/></Link>}</aside></section>
}
